// Auto-generated from File-thần số học.xlsx — do not hand-edit, regenerate from source.

export const LIFE_PATH_SHORT = {
  1: "NHÀ LÃNH ĐẠO BẨM SINH",
  2: "TỐT BỤNG NGOẠI GIAO TỐT",
  3: "THÍCH NỔI BẬT",
  4: "NGƯỜI LẬP KẾ HOẠCH THỰC CHIẾN",
  5: "NGƯỜI PHIÊU LƯU",
  6: "TÌNH YÊU",
  7: "THÔNG MINH & BÍ ẨN",
  8: "SINH RA ĐỂ THÀNH ÔNG CHỦ",
  9: "TÂM HỒN HOÀI CỔ",
  11: "TRỰC GIÁC NHẠY BÉN",
  22: "NGƯỜI KIẾN TẠO ĐẠI TÀI",
  33: "NHÀ GIÁO ĐẠI TÀI",
};

export const LIFE_PATH_TEXT = {
  1: "Bạn là một nhà lãnh đạo bẩm sinh, có nhiều suy nghĩ, phát minh, ý tưởng và tầm nhìn độc đáo. Mặc dù rất thành thạo trong việc bắt đầu mọi thứ, bạn không phải là người xuất sắc trong việc nhìn nhận tổng thể, từ đầu đến cuối. Những chi tiết tẻ nhạt có thể khiến bạn mất hứng thú.\n\nTrong các mối quan hệ, điều quan trọng là bạn phải giữ được sự độc lập của mình, nhưng bạn cũng muốn bản thân là một phần quan trọng và cần thiết. Bạn thích chịu trách nhiệm - tuy nhiên, bạn phải nỗ lực để tránh trở nên độc đoán và ích kỷ.\n\nBạn có khả năng và tự tin, tuy nhiên, bạn cũng gặp khó khăn vì tự kỷ ám thị. Hãy nhớ đừng quá khắt khe với chính mình, nếu không chính điều này có thể cản trở khả năng tiến bộ và đạt được mục tiêu của bạn.\n\nĐiều vô cùng quan trọng là bạn phải nỗ lực để phát triển ý thức cá nhân để chính bạn có thể rút ra các bài học và chủ động cải thiện cuộc sống và các mối quan hệ của mình.\n\nKhi nói đến sự nghiệp, nhiều người có con số đường đời 1 là doanh nhân hoặc ông chủ, họ không thích bị chỉ bảo phải làm gì. Bạn có tính cạnh tranh gay gắt, điều này giúp bạn vươn lên dẫn đầu. Nhiều vận động viên chuyên nghiệp thành công và vận động viên Olympic cũng có con số đường đời này. Nếu không được giải tỏa, năng lượng cạnh tranh trong bạn có thể trở nên quyết liệt và hủy diệt. Bạn phải học cách giữ bình tĩnh. Sự hài lòng tức thì và kết quả trước mắt là thứ thúc đẩy bạn, điều này có thể khiến bạn bốc đồng và thiếu quan tâm đến người khác.\n\nNhững người có số đường đời 1 thường gặp các vấn đề sức khỏe liên quan đến hệ tiêu hóa. Họ cũng có thể bị chứng đau nửa đầu, nghiện ngập và các tình trạng liên quan đến căng thẳng như đau vai và lưng.\n\nĐường thẳng tạo thành số 1 đại diện cho ranh giới bạn cần dựng lên. Nó cũng cho thấy cách số 1 đứng 1 mình: 1 cá nhân duy nhất phấn đấu cho vị trí hàng đầu.",
  2: "Tốt bụng, ngoại giao tốt và có tinh thần hợp tác đều là những đặc điểm nổi bật của con số đường đời 2. Bạn là người kiên nhẫn nhất trong tất cả các con số và cực kỳ nhạy cảm, nhạy bén và giàu cảm xúc. Cảm xúc của bạn có thể chuyển từ khóc sang cười. Cùng với sự nhạy cảm đó là những khả năng về trực giác, bạn có khả năng bẩm sinh để cảm nhận cảm xúc của người khác. Tuy nhiên bạn phải chắc chắn không hy sinh ý kiến và cảm xúc cá nhân hoặc thỏa hiệp chỉ để giữ hòa khí, vì điều này có thể tạo ra sự oán giận.\n\nKhi nói đến các mối quan hệ, bản chất kiên nhẫn, thích thỏa hiệp của bạn có thể thu hút những người cố chấp thay vì một người bạn đời phù hợp và chín chắn. Bạn khó có thể sống độc thân lâu và có thể trải qua nhiều mối tình, chuyển từ người này sang người khác. Bạn cảm thấy thoải mái khi có đôi có cặp hơn là sống một mình.\n\nBạn là một nhà đàm phán và hòa giải bẩm sinh. Không phải lúc nào bạn cũng nhận được sự tín nhiệm hoặc công nhận mà bạn xứng đáng. Bạn có thể quan tâm quá mức đến những gì người khác nghĩ. Bạn sẽ thành công trong nghề nghiệp cho phép bạn giúp đỡ người khác, các lĩnh vực như hòa giải, giảng dạy hoặc tư vấn. Con số đường đời 2 cũng là những người có khiếu thẩm mỹ đặc biệt. Họ có thể áp dụng kỹ năng này vào công việc thiết kế hoặc các hoạt động nghệ thuật. Họ cũng có thể thể hiện kỹ năng đàm phán mạnh mẽ và thể hiện sự thông minh trong lĩnh vực chính trị hoặc luật pháp.\n\nMức độ nhạy cảm của con số đường đời này mở rộng đối với tất cả các loại chất gây dị ứng, bao gồm thực phẩm, sản phẩm chăm sóc da và tóc, bụi, hóa chất, dược phẩm và nhiều loại khác. Các vấn đề sức khỏe khác có thể gồm lo lắng thái quá, trầm cảm và các vấn đề về dạ dày.\n\nSố 2 có dáng cong và cho thấy sự thỏa hiệp, vì vậy bạn cần phải học cách đứng lên bảo vệ chính mình.",
  3: "Con số đường đời 3 thích nổi bật! Bạn sống \"cuộc sống của những bữa tiệc'', được yêu thích và quảng giao. Năng lượng của bạn thúc đẩy sự mở rộng. (nếu bạn kể 1 câu chuyện cho những người có con số đường đời 3, họ sẽ cải biến câu chuyện khi kể lại cho người khác, sử dụng các từ hoa mỹ, nhấn nhá và chắc chắn là thêm 1 số chi tiết cường điệu). Sự lạc quan và nhiệt tình của bạn có khả năng lan truyền. Bạn cần giải tỏa năng lượng sáng tạo của mình, nếu không nó sẽ bùng nổ dưới dạng cảm xúc.\n\nCảm xúc của bạn có thể dễ dàng bị tổn thương, đặc biệt là bằng lời nói, điều này thật trớ trêu, vì bản thân bạn cũng có cái lưỡi sắc bén và hiếm khi gặp khó khăn trong việc thể hiện bản thân. Trên thực tế, bạn phải cẩn trọng để xem mình có đang hỗn xược, hoài nghi hoặc ủ rũ không. Hãy nhớ rằng lời nói của bạn có thể làm tổn thương người khác, vì vậy hãy cẩn thận khi sử dụng chúng. Bạn có thể rất khắt khe với bản thân và có tâm lý tự ti. Bạn sử dụng năng khiếu hài hước của mình để che giấu cảm xúc bị tổn thương và sự bất an, nhưng cách đối phó này có thể bị nhận ra dễ dàng hơn bạn nghĩ.\n\nNhìn chung, bạn cần thêm hành động chủ động vào những mối quan hệ thân thiết nhất của mình để mọi người xung quanh cảm thấy họ được trân trọng.\n\nTài năng nghề nhiệp của con số đường đời này là sự sáng tạo. Nhạc sĩ, diễn viên, nghệ sĩ, vũ công, nhà văn, đầu bếp là 1 vài lựa chọn nghề nghiệp nổi trội để bạn cân nhắc. Ở mức độ rung động thấp, bạn có thể thoái thác trách nhiệm, sống vô tổ chức và chìm đắm trong tâm lý nạn nhân, phẫn nộ với bất kỳ ai tranh giành sự chú ý với bạn. Khi nỗ lực hết mình và thể hiện sự tích cực, bạn có thể trở thành nguồn động lực truyền cảm hứng, nâng cao tinh thần và mang lại niềm vui cho những người xung quanh.\n\nVề sức khỏe, bạn có khả năng tăng và giảm cân nhanh chóng, đôi khi ở mức báo động. Hầu hết những người có con số đường đời 3 đều được ban cho vẻ ngoài ưa nhìn và nụ cười đẹp. Cân nặng luôn dao động, trạng thái tinh thần và các vấn đề về họng là những vấn đề sức khỏe mà bạn cần chú ý.\n\nSố 3 có hình dáng giống như một cặp móng ngựa nằm ngang và được coi là con số may mắn nhất. Đừng bao giờ coi vận may của bạn là điều hiển nhiên!",
  4: "Bạn là 1 người lập kế hoạch thực chiến, luôn đọc các hướng dẫn cẩn thận và chuẩn bị sẵn sàng trong mọi tình huống. Bạn là người đáng tin cậy. Tận tâm và hành động nhanh chóng. Những điều bất ngờ và thay đổi là điểm yếu của bạn. Bạn mong muốn kiểm soát kết quả, vì vậy bạn cần học được cách quản lý và đón nhận sự thay đổi cũng như tin tưởng vào sức mạnh vô hình của cuộc sống. Là người bi quan trong lòng, ngay cả vào một ngày đẹp trời, bạn vẫn nhìn ra những đám mây ở phía xa và mang theo ô đi làm.\n\nNhững ranh giới kiên cố bảo vệ bạn, nhưng điều quan trọng là phải học cách linh hoạt và chấp nhận sự giúp đỡ của người khác. Tính cách thực tế của bạn luôn không cho phép bạn đối xử tốt với bản thân, phung phí hoặc trải nghiệm khía cạnh xa hoa của cuộc sống.\n\nBất chấp tính kỷ luật, sự trì hoãn có thể là vấn đề đối với bạn. Những người có số 4 khá kỷ luật và muốn kiểm soát mọi thứ và mọi người. Ở độ rung động thấp, bạn có thể rất tính toán và thích thao túng. Hãy chắc chắn rằng bạn luôn kiểm soát được cái tôi của mình.\n\nBạn là người thân thiện 1 cách tự nhiên nhưng có xu hướng không để người khác đến quá gần. Điều quan trọng là phải thể hiện mặt yếu đuối của bản thân để phát triển các mối quan hệ thân thiết. Khi trung thực là tính cách mặc định của bạn, người khác sẽ biết bạn là người đáng tin cậy.\n\nNhững người có số đường đời này có xu hướng tìm kiếm thành công trong các lĩnh vực như giáo dục, kinh doanh, chăm sóc sức khỏe, quản trị, xây dựng, chính trị và kế toán. Họ là những người xây dựng, kiến tạo. Một nền tảng vững chắc và một khoản tiết kiệm là tất cả những gì bạn cần để cảm thấy an tâm và hạnh phúc.\n\nVấn đề sức khỏe thường gặp cho nhóm người này là các bệnh liên quan đến căng thẳng như đau khớp, đau nửa đầu, đau bụng, các vấn đề về lưng, ám ảnh cưỡng chế và chứng rối loạn lo âu.\n\nSố 4 hình thành từ các đường thẳng, thể hiện nhu cầu duy trì trật tự và hiệu quả. Hãy nhớ luôn duy trì sự linh hoạt.",
  5: "Thắt dây an toàn vào nào! Cuộc sống của người này là 1 chuyến đi thú vị và không thể đoán trước. Bốc đồng và luôn sẵn sàng cho bất cứ điều gì, bạn thích phiêu lưu, tự do và du lịch. Các quy tắc chỉ có tính định hướng với bạn và bạn có xu hướng bẻ cong và bất chấp chúng theo ý muốn của mình. Sự buồn chán có thể dẫn đến chủ nghĩa thoát ly, điều này có thể nhanh chóng chuyển sang trạng thái tự hủy hoại bản thân. Bạn tiêu tiền cho những chuyến đi du lịch và trải nghiệm hơn là những thứ vật chất. Bạn có thể là nguồn cơn lo lắng của gia đình.\n\nKhi nói đến các mối quan hệ, bạn có thể hơi khó kìm nén và gặp khó khăn để giữ cam kết. bạn là người gợi cảm và đòi hỏi sự đa dạng và kích thích liên tục. Bạn có khả năng cam kết và trung thành, nhưng đó phải là mong muốn của bạn. Bạn nên tránh kết hôn khi còn trẻ vì có thể đó sẽ là cuộc hôn nhân thất bại.\n\nNhững người có số đường đời 5 thường đa tài và bạn sẽ thành công trong hầu hết mọi thứ mà bạn quan tâm. Bạn có quan điểm tiến bộ và là người đầu tiên đón nhận những ý tưởng mới. Bạn dễ dàng thích nghi, vì vậy công nghệ có thể là một lựa chọn nghề nghiệp tuyệt vời. Bạn là người kể chuyện tự nhiên và xuất sắc trong việc thúc đẩy và truyển cảm hứng cho người khác. Bạn hoàn toàn có thể bán bất cứ thứ gì với sự quyến rũ và đáng yêu của mình. Những đặc điểm này có thể đưa bạn đến với sự nghiệp quảng cáo, tiếp thị, làm việc tại công ty khởi nghiệp hoặc tạo mẫu tóc. Bạn cũng thường bị thu hút bởi những công việc mặc đồng phục, chẳng hạn như lực lượng an ninh, người thực thi pháp luật, phi công hoặc tiếp viên hàng không. Nhiều người cũng có lòng hiếu khách. Và cũng luôn có các công việc tự do để bạn lựa chọn. khi đó không ai có thể gò bó phong cách của bạn hay đặt câu hỏi về việc bạn nghỉ ngơi! Bạn cũng có năng khiếu bẩm sinh về ngôn ngữ.\n\nỞ mức độ rung động thấp, bạn có xu hướng nhận về mình ý tưởng hoặc công việc không phải của bạn. Điều này có thể gây tổn hại đến danh tiếng của bạn và khiến mọi người phật lòng. Bài học của bạn nằm ở sự chăm chỉ, kiên trì và thể hiện sự ghi nhận khi cần thiết.\n\nNgười có con số đường đời 5 dễ gặp các vấn đề về cảm xúc nghiện ngập, suy kiệt tuyến thượng thận và đau khớp. Hãy nhớ uống đủ nước để tránh mất nước.\n\nHình dạng của số 5 mở ra cả bên phải và bên trái, thẳng ở trên và cong ở dưới. Điều này cho thấy nhu cầu về sự đa dạng và thay đổi liên tục. Hãy nhớ giữ bình tĩnh và kiên định.",
  6: "Rung động của số 6 là về TÌNH YÊU! Quyến rũ và lôi cuốn, với tính cách thu hút, bạn có khả năng hấp dẫn mọi người đến bất kỳ công việc nào bạn làm. Nhờ sự hào phòng, tốt bụng và hấp dẫn, bạn được ngưỡng mộ và thậm chí được yêu mến (điều này có thể khiến bạn bối rối). Bạn là người yêu thích tụ tập mọi người và cũng là người yêu động vật. Bạn giúp đỡ mọi người mà không đơn giản là bày tỏ sự thông cảm. Tính cách của bạn khá cực đoan. Người có con số đường đời 6 có phẩm chất ma quỷ hoặc thiên thần.\n\nBạn là một cá nhân giàu lòng nhân ái và là một người bạn tuyệt vời, trung thành đến cùng. Thật không may, lòng trung thành đó không phải lúc nào cũng được đáp lại. Một trong những bài học của bạn sẽ là hiểu và trải nghiệm ý nghĩa thực sự của sự phản bội, đôi khi có thể là trải nghiệm đau đớn. Bạn có xu hướng thu hút những người bị tổn thương, và bạn cần cảm giác bản thân là người có ích. Trong các mối quan hệ, bạn phải học cách cân bằng giữa giúp đỡ và can thiệp.\n\nNgười có con số đường đời 6 thường thành công trong lĩnh vực giảng dạy, khách sạn, tâm lý học, quản lý, bất động sản, chính phủ, các ngành nghề liên quan đến động vật hoặc lĩnh vực thẩm mỹ như thời trang hay thiết kế nội thất. Bạn hiểu những thứ xa hoa trong cuộc sống hơn bất kỳ ai khác. Quan điểm cứng rắn của bạn cũng khiến bạn gặp rắc rối. Nếu thấy mình luôn trong tình trạng căng thẳng về tài chính, bạn đang không sống đúng với mục đích của mình. Những người có số 6 yêu nhiều, đôi khi quá nhiều, vì họ cũng có xu hướng cất giấu tình cảm trong lòng. Các vấn đề sức khỏe thường gặp liên quan đến khả năng sinh sản và các vấn đề tim mạch.\n\nHình dạng của số 6 giống như một phụ nữ mang thai. Một điều không bao giờ thay đổi đối với số 6: tầm quan trọng của gia đình. Các bậc cha mẹ có con số đường đời này cảm thấy khó khăn khi nhìn con cái lớn lên, trưởng thành, độc lập và phải kháng cự lại thôi thúc can thiệp. Cho dù bạn có quyết định lập gia đình hay không, bạn vẫn luôn có những hành động tuyệt vời để chăm sóc người khác.",
  7: "Bạn là người thông minh và bí ẩn, thuộc kiểu người mạnh mẽ và trầm lặng. Bạn thích phân tích, tự nghiên cứu và không bao giờ nhìn nhận mọi thứ qua bề nổi. Nếu ai đó có bí mật, bạn sẽ tìm thấy nó.\n\nBản chất bạn là người đa nghi và tò mò. Bạn bẩm sinh có trực giác nhạy bén, tâm linh và siêu hình học là những bí ẩn thu hút bạn. Điều quan trọng đối với bạn, với tư cách là người có số đường đời 7, là phải có niềm tin tâm linh hoặc tôn giáo. Nếu không, cuộc sống của bạn có thể thiếu mục đích. Các yếu tố có tính chất lịch sử hoặc những câu chuyện xa xưa đều khiến bạn thích thú. Số 7 cũng thích lưu trữ thông tin, thường có cả giá sách chưa đọc.\n\nKiến thức và sự nhanh trí của bạn mang lại cho bạn khiếu hài hước độc đáo và giúp bạn trở nên thu hút và được ngưỡng mộ. Tuy nhiên, bạn lại gặp khó khăn trong việc duy trì các mối quan hệ thân thiết, vì dường như bạn đang kìm hãm và giữ bí mật. \n\nHãy thẳng thắn và trung thực trong giao tiếp. Ở độ rung động thấp, các bài học khác sẽ bao gồm sự ghen tị khi yêu cũng như các vấn đề về cái tôi. Bạn sẽ học cách duy trì và tôn trọng các ranh giới và quyền riêng tư của người khác cũng như những gì có thể vi phạm ranh giới của chính bạn.\n\nỞ độ rung động cao, bạn sở hữu từ tính bí ẩn. Bạn quyến rũ, thông minh, hài hước và hấp dẫn. Bạn thích làm cho người khác cảm thấy thoải mái, mặc dù trong tâm trí bạn vẫn có những phán xét hay đánh giá riêng.  Những người sở hữu số 7 mà không có số 3 ở gần để cân bằng có thể trở nên ẩn dật và chống đối xã hội.\n\nNhững người có con số đường đời 7 sẽ thành công ở lĩnh vực nghề nghiệp như nghiên cứu, sử học, quản lý bảo tàng., lập hồ sơ tội phạm, giáo viên thần học hoặc tôn giáo hay luật sự. Bạn thích làm việc 1 mình. Số 7 thường sẽ chỉ làm việc cho 1 số công ty hoặc tổ chức trong sự nghiệp của mình.\n\nBạn thường bị khó ngủ. Bạn cũng có thể gặp các vấn đề về cổ vì là người luôn bận rộn. Thiền, yoga, tắm hoặc đi bộ đường dài có thể giúp bạn tĩnh tâm và thư giãn.\n\nHình dạng số 7 như 1 boomerang, phản ánh chính nó trong các mối quan hệ, hoàn cảnh sống và sự nghiệp. Bạn thường thấy mình quay trở lại với những người, công việc và địa điểm giống nhau, chân của số 7 không có điểm tựa. Việc mất cân bằng có thể dẫn đến trầm cảm, nghiện ngập và mất ngủ.",
  8: "Nếu không phải là người chịu trách nhiệm, bạn sẽ giả vờ hay tỏ ra như vậy. Bạn là người có tầm nhìn xa và cũng khá liều lĩnh. Hãy nhớ rằng có 1 ranh giới giữa quyền lực và tham nhũng, và bạn phải bước đi trên ranh giới đó 1 cách cẩn thận. Bạn thích tiền và tiêu xài hoang phí. Những việc bạn làm liên quan đến tiền sẽ phản tác dụng nếu bạn làm vì mục đích sai trái. Tuy nhiên, bạn có thể đạt được thành công nếu làm việc với sự chính trực và thành thật. Bạn phải nhớ rằng phần thưởng không phải lúc nào cũng xuất hiện dưới dạng tiền bạc, chúng cũng có thể là sự công nhận và di sản. Số 8 trải qua nhiều thăng trầm trong cuộc sống.\n\nViệc thể hiện tình yêu và tình cảm là điều khó khăn với bạn. Hãy ngừng cố chấp và kiểm soát. Cuộc sống của bạn có thể là cánh cửa xoay tròn của các mối quan hệ và tình bạn. Ở độ rung động thấp, bạn có thể gặp khó khăn trong việc trung thành và giữ bí mật và có thể bị coi là đạo đức giả. Cái tôi, sự kiêu ngạo và ích kỷ có thể là điểm yếu của bạn. Bạn dễ nổi giận nhưng cơn giận luôn nhanh chóng qua đi. Bạn học hỏi từ những kinh nghiệm này. Hãy học cách chịu trách nhiệm, thành thật xin lỗi và tiến bộ.\n\nSố 8 thường trải qua nhiều công việc tại các công ty khác nhau, cố gắng tìm ra môi trường phù hợp. Với con số đường đời 8, bạn sẽ hoàn thành xuất sắc mọi công việc trong môi trường kinh doanh và đây cũng là lĩnh vực bạn có lợi thế và tạo được sự ảnh hưởng, như ngân hàng, bất động sản, tài chính và báo chí. Bạn giỏi công tác tổ chức, huấn luyện, giám sát và chỉ đạo. Bạn được thúc đẩy bởi tiền bạc, quyền lực và sự công nhận. Hãy luyện tập và cải thiện sự khéo léo của bạn để ý tưởng của bạn được tiếp nhận tốt hơn.\n\nNhững thách thức về sức khỏe với số 8 là các vấn đề liên quan đến căng thẳng như huyết áp cao và vấn đề tim mạch.\n\nHình dạng số 8 được tạo thành từ 2 vòng tròn dính liền thể hiện tinh thần và vật chất. Bạn phải luôn giữ cho 2 mặt này cân bằng. Nếu không có sự cân bằng, số 8 sẽ không bao giờ tìm thấy sự hài lòng thực sự. Hình dạng đối xứng này cũng có nghĩa là bạn có thể đảo ngược hoàn toàn và toàn bộ bất cứ lúc nào.",
  9: "Những người sở hữu con số đường đời 9 có năng lượng của một tâm hồn hoài cổ. Nhiều kiếp trước mang lại cho bạn sự khôn ngoan trong tiềm thức. Bạn có khiếu hài hước, thông minh và dí dỏm. Bạn lan truyền tiếng cười đến mọi người. Số 9 cũng có trực giác tuyệt vời. Bạn là người không bốc đồng và thường suy nghĩ xa xôi.\n\nLuận điểm bạn đưa ra rất khó để tranh luận (mặc dù đôi khi điều này sẽ rất mệt mỏi nếu bạn là người sai). Là 1 học sinh giỏi với khả năng đọc nhanh, bạn tiếp thu thông tin như một miếng bọt biển và duy trì việc học trong suốt cuộc đời.\n\nBạn quyến rũ, hấp dẫn, lãng mạn và không gặp khó khăn khi thu hút bạn đời. Tuy nhiên, thật khó để tìm được 1 người có trí tuệ như bạn hoặc người có thể chia sẻ khiếu hài hước và thực sự khiến bạn cười.\n\nỞ độ rung động thấp, bạn có thể hạ mình. Bạn có xu hướng giải thích quá mức mọi thứ, rằng người khác không thể hiểu được. Bạn cũng có thể là kẻ thù tồi tệ nhất của chính mình, tự hủy hoại bản thân ngay khi đang trên bờ vực thành công.\n\nTrong sự nghiệp, bạn mong muốn giúp đỡ mọi người, bạn có thể tìm thấy sự thỏa mãn bằng cách truyền cảm hứng cho người khác bằng ý tưởng của mình với tư cách là 1 nhà văn, nghệ sĩ hoặc nhà làm phim. Các ngành nghề giảng dạy, tư vấn, chăm sóc sức khỏe, kinh doanh quốc tế cũng là những lựa chọn tốt cho bạn. Bạn cũng là 1 nhà nhân đạo và từ thiện bẩm sinh, người không tìm kiếm sự khen ngợi hay công nhận cho những việc làm tốt của mình. Bạn thông minh đến mức nếu bạn tận dụng sự khôn ngoan của mình để phạm tội, bạn cũng có thể thành công, mặc dù cuối cùng bạn sẽ phải trả giá (nếu không ở kiếp này thì là kiếp sau).\n\nBạn có xu hướng không thể hiện hoặc đối phó với cảm xúc trên tinh thần xây dựng. Cảm xúc này tích tụ và dẫn đến chứng đau cổ và vai, đặc biệt là hông. Bạn phải luôn rèn luyện thể chất. Một mối quan tâm sức khỏe khác là tình trạng tự miễn dịch của cơ thể.",
  11: "Con số Vua 11 có trực giác nhạy bén. Bạn có thể đi trước thời đại và thế giới có thể chưa sẵn sàng cho những gì bạn phải đem đến. Do đó, nhóm 11 thường không ngay lập tức gặt hái được thành quả từ sự cần mẫn tiên phong của mình.\n\nNhờ tinh thần tiên phong, người có con số vua 11 trở thành những diễn giả truyền cảm hứng tuyệt vời, những nhà lãnh đạo tinh thần, người dẫn chương trình truyền hình, nhà thiết kế hoặc nhân vật truyền thông.\n\nNgười thuộc nhóm này thích ở trong 1 mối quan hệ, đặc biệt là một mối quan hệ bình yên, hài hòa. Họ đem cảm giác nhẹ nhàng và những đặc điểm tính cách của mình vào các mối quan hệ.\n\nBởi vì 11 cảm nhận mọi thứ quá sâu sắc nên có thể dẫn đến trầm cảm, lo lắng và tình trạng dị ứng nghiêm trọng. Sự rung cảm độc đáo của số 11 kéo theo các vấn đề sức khỏe của cả số 1 và số 2.",
  22: "22 được gọi là người kiến tạo đại tài. Con số vua 22 là những người có khả năng đặc biệt, biến tầm nhìn thành hiện thực. Việc xây dựng đế chế và để lại di sản là điều vô cùng quan trọng với họ.\n\nBời vì 22 mang năng lượng gấp đôi của số 2, người thuộc nhóm này thường sống trong căng thẳng, lo lắng và phải học cách tham gia vào các kế hoạch có tầm nhìn xa. Người 22/4 sẽ phải chịu thử thách về đạo đực và trách nhiệm. Nguồn gốc của gia đình họ có xu hướng phức tạp.\n\nSố 22 sẽ tìm kiếm 1 người bạn đời có thành tích cao để tạo cho họ cảm giác an toàn. Họ bị thu hút bởi những người có quan điểm thực tế và tập trung vào mục tiêu.\n\nHọc cách tin tưởng vào người khác, thay vì cố gắng kiểm soát hoặc thao túng họ là bài học cho nhóm người này. Chia sẻ tầm nhìn của bạn và để mọi người tham gia góp ý. Bạn cần những điều này nhiều hơn bạn nghĩ đấy.\n\nSố 22 là người cực đoan và có thể sử dụng sức mạnh của mình cho cả điều thiện hoặc ác. Phần thưởng lớn nhất của bạn sẽ đến từ những nỗ lực làm việc thiện và có mục đích tốt\n\nHọ là nhóm người thích đặt tên mình lên tất cả mọi thứ. Sự rung cảm độc đáo của số 22 kéo theo các vấn đề sức khỏe của cả số 2 và số 4 như dị ứng và căng thẳng.",
  33: "Họ là những người có sức ảnh hưởng và cảm thông lớn nhất trong các con số Vua (11/22/33). Nằm trong nhóm 33, bạn là người hiểu biết và nghiên cứu kỹ lưỡng tất cả các ý tưởng của mình trước khi chia sẻ chúng. Khi đạt đến tiềm năng cao nhất, bạn có khả năng giao tiếp, truyền đạt rõ ràng mà không cần chuẩn bị chương trình cụ thể, và bạn thực sự quan tâm đến nhân loại.\n\nTrong 1 mối quan hệ, bạn cần tập trung vào việc làm chủ cảm xúc của mình. Vì có sức hút và sự hấp dẫn nên bạn không bao giờ gặp khó khăn trong việc tìm kiếm đối tác. Tuy nhiên, hãy cẩn thận với những tính cách phức tạp, đó là sự thiếu thốn nhưng không sẵn lòng giúp đỡ chính mình.\n\nNhóm này thích giúp đỡ và chữa lành cho mọi người. Cảm giác thỏa mãn đến từ việc giúp đỡ người khác và sự chia sẻ khôn ngoan và năng khiếu nghệ thuật với thế giới. Bạn phù hợp với những nghề nghiệp như hỗ trợ nhân quyền, giáo dục, chăm sóc sức khỏe và nghệ sĩ thuộc mọi phương tiện. Hãy tự chăm sóc bản thân.\n\nSự rung cảm độc đáo của số 33 kéo theo các vấn đề sức khỏe của cả số 3 và số 6, cả vấn đề sinh sản và tim mạch cũng như trầm cảm và cân nặng dễ biến động.",
};

export const DESTINY_SHORT = {
  1: "NGƯỜI LÃNH ĐẠO & RA QUYẾT ĐỊNH",
  2: "NGƯỜI ĐỒNG ĐỘI TỐT",
  3: "NGHỆ SĨ & NHÂN VẬT GIẢI TRÍ",
  4: "NGƯỜI LẬP KẾ HOẠCH VÀ NHÀ SẢN XUẤT",
  5: "NGƯỜI TÌM KIẾM SỰ MẠO HIỂM",
  6: "NGƯỜI THEO CHỦ NGHĨA HOÀN HẢO",
  7: "NGƯỜI CÓ TRỰC GIÁC THÔNG MINH",
  8: "NGƯỜI ĐIỀU HÀNH",
  9: "NGƯỜI CÓ TẤM LÒNG NHÂN ĐẠO",
  11: "NGƯỜI CÓ TRỰC GIÁC NHẠY BÉN",
  22: "KIẾN TRÚC SƯ TÀI BA",
  33: "NHÂN VẬT CÓ TẦM ẢNH HƯỞNG",
};

export const DESTINY_TEXT = {
  1: "Bạn thích làm như vậy theo cách riêng của mình và thường làm như vậy. Trong sự nghiệp, bạn tìm kiếm không gian phát triển để duy trì động lực, và nhiều khả năng sẽ vươn lên vị trí người chịu trách nhiệm.\nSự sáng tạo giúp bạn có kỹ năng giải quyết vấn đề nhanh chóng.\n\nBạn có tầm nhìn xa tuyệt vời và những ý tưởng sáng tạo, đồng thời xuất sắc trong việc thu hút mọi người cùng tham gia để biến ý tưởng của bạn thành hiện thực. Số 1 cũng hào hứng với các ý tưởng, thực sự hào hứng, nhưng có thể mất hứng khi đi vào chi tiết và thường phải gặp khó khan để duy trì và kết thúc toàn bộ quá trình. Hãy nhớ đặt các ranh giới và đứng lên bảo vệ chính mình.\n\nBạn sợ thất bại. Nếu không nghĩ rằng mình giỏi nhất ở lĩnh vực nào đó, bạn thậm chí sẽ không thử. Ở mặt tối tính cách, bạn có thể hách dịch, thiếu kiên nhẫn, kiêu ngạo, ích kỷ và lạm dụng sức ảnh hưởng của mình cho những mục đích xấu.\n\nHãy đón nhận và phát huy tài năng thiên bẩm và lãnh đạo, khả năng truyền cẩm hung, suy nghĩ độc lập và những ý tưởng độc đáo. Hãy sẵn lòng chia sẻ tính sáng tạo của bạn. Cuối cùng, con số vận mệnh 1 đòi hỏi bạn phải tận dụng những tài năng này và tạo cơ hội để hoàn thành tầm nhìn của mình.",
  2: "Con số vận mệnh 2 bẩm sinh là những người khéo léo, duyên dáng, giỏi chi tiết, hợp tác và kiên nhẫn. Bạn xuất sắc với tư cách là 1 phần của nhóm và tốt hơn trong mối quan hế đối tác hơn là vị trí lãnh đạo.\n\nBạn có xu hướng đoán già đoán non về bản thân và thiếu tự tin vào lựa chọn của mình. Sự nhạy cảm giúp bạn làm tốt việc trong nhóm và tạo được sự cân bằng tinh tế ở nơi làm việc. Vì thích trở thành tâm điểm chú ý bạn phải chắc chắn rằng những người khác nhận ra và cảm kích những nỗ lực của bạn hay dành cho bạn sự công nhận, nếu không bạn có thể bị phớt lờ. Mọi người tin tưởng bạn và yêu mến tính cách quan tâm và hào phóng của bạn. Nếu không cảm nhận được sự tôn trọng này, bạn sẽ cảm thấy không thoải mái hoặc không làm tốt công việc.\n\nỞ mặt tối tính cách, bạn thường quá nhạy cảm, hay khóc, lén lút, lôi kéo và nói dối thuần thục, bộc lộ 2 mặt đối lập về tính cách. Bạn có thể trở nên đối đầu thay vì khéo léo ngoại giao.\n\nBạn sẽ vui vẻ nhất khi có đóng góp tích cực và năng động trong hoạt động của đội nhóm. Mang lại sự hòa hợp, cân bằng và hợp tác khi làm việc, bạn cảm thấy thỏa mãn và vượt qua được mặt tối của mình. Cho dù đó là với gia đình, bạn bè hoặc đồng nghiệp, hãy là người hòa giải và mang lại sự ảnh hường hài hòa trong bất cứ tính huống nào mà bạn cảm thấy cần thiết.",
  3: "Cùng với sự sáng tạo quá mức, con số vận mệnh 3 có thể mắc hội chứng Peter Pan và không bao giờ muốn lớn lên. Bạn có 1 khiếu hài hước tuyệt vời và thích công việc là trải nghiệm vui vẻ và thăng hoa. \n\nNhững điều này hoàn toàn tốt nhưng bạn cũng phải thực hiện trách nhiệm của mình 1 cách nghiêm túc. Những gì mà người khác công nhận và khuyến khích là tài năng thiên bẩm của bạn có thể không phải là thứ mang lại cho bạn niềm vui. Điều quan trọng là phải cố gắng giữ được sự cân bằng. Bên cạnh niềm vui, bạn cũng trải qua mọi cung bậc cảm xúc ở mức độ mãnh liệt. Cố gắng kiềm chế sự nhạy cảm của bạn và không nhìn nhận mọi thứ 1 cách quá cá nhân.\n\nNhững người khác có thể cảm thấy bạn có 1 cuộc sống hấp dẫn và thấy ghen tị vì mọi thứ luôn suôn sẻ với bạn. Mặt khác bạn cảm thấy ghen tỵ với bất kỳ ai mà bạn cho là phá hủy tầm ảnh hưởng của bạn hoặc người có vẻ tài năng, nổi tiếng hoặc năng khiếu hơn bạn. Hãy nhớ rằng có rất nhiều cách để thành công.\nỞ mặt tối tính cách, nhóm 3 phải tránh quá kịch tính hoặc cảm tính, lừa dối, cố chấp và ghen tuông. Hãy kiểm soát những cảm xúc trẻ con này và bạn sẽ trải nghiệm nhiều hơn niềm vui mà bạn đang tìm kiếm.",
  4: "Bạn là người đáng tin cậy, có tổ chức và đúng giờ. Bạn có thể bực bội với những người không thích điều này, nhưng bạn cũng có ký năng để quản lý họ. Bạn có khả năng tuyệt vời trong việc giữ bình tĩnh khi đối mặt với hỗn loạn và mang lại trật tự cho mọi việc bạn làm.\n\nNhững thành tựu thực tế đem đến cho bạn sự hài lòng, như trả hết tiền mua xe hoặc có 1 ngôi nhà tươm tất. Tuy nhiên, nhu cầu kiểm soát mọi thứ là ám ảnh đối với bạn, và bạn phải học cách từ bỏ nó.\nBạn luôn là người có kế hoạch nhưng những người khác thường không để ý đến những vất vả mà bạn đã làm. Bạn có thể chia nhiệm vụ thành từng phần nhỏ và hoàn thành từng bước, mặc dù thực tế là bạn không thích người khác can thiệp vào công việc của mình.\n\nỞ mặt tối tính cách bạn có thể là một người tham công tiếc việc, cố chấp hay phản kháng và thất thường. Sự phẫn uất có thể khiến bạn trở nên tàn nhẫn. Học cách phân công công việc, trao quyền cho người khác và dành nhiều thời gian hơn để giải trí là điều quan trọng đối với bạn. Nếu bạn có nợ nghiệp 13/4 (tổng 4 đến từ con số 13) bài học chính trong cuộc đời bạn là sẽ nỗ lực để hoàn thành mọi việc.",
  5: "Bạn luôn có những câu chuyện để kể, những nơi để đến, những chuyến đi để thực hiện và những người để gặp. Những người khác ngưỡng mộ tinh thần mạo hiểm của bạn và muốn có cuộc sống như bạn. Bạn phải nhớ đừng đưa mọi thứ đi quá xa và cuộc sống vẫn thú vị mà không bị hủy hoại.\nĐể đạt được sự thỏa mãn trong sự nghiệp của mình, bạn sẽ cần rất nhiều thứ, vì vậy cuộc sống văn phòng có thể không phù hợp với bạn. Tính cách lôi cuốn và năng khiếu thu hút sự chú ý của bạn phù hợp với công việc bán hàng, tiếp thị hoặc quảng cáo.\n\nBạn có thể bị cuốn vào những bộ phim truyền hình hoặc những câu chuyện phiếm, đôi khi tự tạo nên 1 kịch bản để giải trí. Vì dễ trở nên buồn chán, bạn có thể thấy xung quanh mình là những người luôn rơi vào khủng hoảng. Để tránh tình trạng này làm tiêu hao năng lượng tuyệt vời của bạn, hãy cố gắng tìm hiểu sâu hơn về bản thân người khác.\nở mặt tối tính cách, bạn có thể bốc đồng, bồn chồn, thẳng thắn, thô lỗ và thậm chí là thô tục. Điều khiến bạn sụp đổ có thể là những lựa chọn điên rồ bạn đưa ra mà không suy nghĩa đến hậu quả. Bạn cũng cần cẩn trọng với xu hướng tự hủy hoại bản thân.",
  6: "Một trong những phẩm chất tốt nhất của bạn là lòng trung thành mặc dù, đáng buồn thay, nó hiếm khi được đáp lại. Con người bạn có thể đã được định hình bởi trách nhiệm gia đình từ khi còn nhỏ. Có một ngôi ngà hạnh phúc và ổn định là điều quan trọng với bạn, và bạn cũng xuất sắc trong các lĩnh vực liên quan đến gia đình. Bạn là một số bậc cha mẹ tuyệt vời và nếu không có con, bạn sẽ dành nhiều công sức cho việc chăm sóc động vật.\n\nBạn là người có óc xét đoán, chín chắn và đáng tin cậy. Trách nhiệm nuôi dưỡng tâm hồn bạn. Bạn có khả năng đánh giá tốt về tính cách và đưa ra những lời khuyên tuyệt vời, đóng vai trò cố vấn cho bạn bè (và có thể cả về chuyên môn). Bạn muốn làm đẹp môi trường xung quanh mình, những thứ xinh đẹp mang lại cho bạn niềm vui và sự thoải mái.\n\nMặt tối tính cách của bạn là sự tự mãn, mỉa mai và tự phụ, suy nghĩ cho rằng không ai có thể làm tốt công việc bằng bạn. Những người khác có thể nhầm lẫn các tiêu chuẩn cao mà bạn đặt ra cho bản thân thành ham muốn cạnh tranh hoặc trịch thượng. Bạn có xu hướng can thiệp, lo lắng và luôn tìm kiếm sự công nhận. Đừng quá chú tâm vào suy nghĩ hoặc vấn đề của người  khác.",
  7: "Bạn tỏa ra phẩm chất của sự trầm lặng. Bạn suy nghĩ sâu sắc về mọi thứ và sự mơ mộng có thể khiến bạn trở thành thiên tài triết học hoặc công nghệ. Bạn đĩnh đạc, dè dặt, tinh ý, tinh tế và duy tâm. Bạn có thể ở 1 mình và không cô đơn, dù đây là điều khó khăn với nhiều con số vận mệnh khác.\n\nTrực giác của bạn mạnh đến mức đôi khi bạn có thể nhìn thấu suy nghĩ của người khác. Những giấc mơ của bạn có khả năng tiên tri. Bạn có trí nhớ tuyệt vời và quan tâm đến lịch sử, các bộ sưu tập và quá khứ. Bạn xuất sắc trong 1 lĩnh vực cụ thể và có thể trở thành chuyên gia thực sự.\n\nNhóm này thường cảm thấy rằng trong quá trình trưởng thành của mình dường như có những bí mật từ cha mẹ. Ngay cả khi điều này là để bảo vệ bạn, cảm giác đó vẫn hình thành và nuôi dưỡng 1 sự nghi ngờ thực sự trong bạn. Bạn là người giữ bí mật và có xu hướng hơi cô độc. Bạn làm việc chăm chỉ, đôi khi trong nhiều năm, hướng  tới mục tiêu trong cuộc sống và công việc của bạn.\n\nMặt tối tính cách của bạn là sự nghi ngờ, không  trung thực, hoang tưởng, lén lút và ghen tị. Bạn có cảm giác tâm linh mạnh mẽ, hay có niềm tin mạnh mẽ vào bất cứ điều gì mà cá nhân bạn thấy có điểm tương đồng, tin rằng điều đó sẽ tạo nên nền tảng, sự cân bằng và giúp bạn phát huy hết khả năng của mình. Bạn hoặc là người rất khoa học hoặc rất duy tâm, tuy nhiên có 1 số người có thể tạo ra sự cân bằng giữa 2 điều này. Hãy vun đắp, nuôi dưỡng ít nhất là 1 vài mối quan hệ thân thiết. Điều quan trọng là phải chia sẻ trí tuệ và kiến thức rộng lớn của bạn với thế giới.",
  8: "Bạn sinh ra để thành công và dồi dào về tài chính. Bạn đã sớm học về quyền lực và địa vị và cần trở thành 1 người có chức quyền trong sự nghiệp mình đã chọn để cảm thấy thỏa mãn. May mắn thay, bạn là một nhà lãnh đạo và người có khả năng ảnh hưởng bẩm sinh.\n\nBạn yêu thích thành tích nhưng hãy cẩn trọng, bạn có thể không bao giờ cảm thấy hài lòng, luôn muốn làm nhiều hơn, nhiều hơn nữa để có nhiều và nhiều hơn nữa. Bạn có xu hướng coi trọng vật chất, nhưng lòng tốt và sự hào phóng mới là di sản đáng quý hơn.\n\nThất bại là điều hủy diệt với bạn, nhưng không cố gắng còn tồi tệ hơn, vì vậy bạn phải dám đối mặt với nỗi sợ hãi của mình. Theo thời gian, bạn sẽ nhận ra mọi người đánh giá, phản hồi về con người của bạn chứ không phải những gì bạn làm hay những gì bạn có.\n\nMặt tối tính cách của bạn là sự thiếu kiên nhẫn, không khoan dung, tàn nhẫn và đôi khi là bạo lực. Bạn có thể lạm dụng chất kích thích và gặp các vấn đề về tài chính. Bạn phải luôn tìm kiếm sự cân bằng. Những mong muốn, khát khao của bạn sẽ được lấp đầy khi bạn mang nền tảng tâm linh vào thế giới vật chất của mình.",
  9: "Bạn có thể thu phục hầu hết mọi người bằng khiếu hài hước; tính cách hướng ngoại & sự quyến rũ của mình. Bạn là người có tầm nhìn xa và có thể truyền cảm hứng cho những người khác tham gia vào một phong trào giúp thế giới trở nên tốt đẹp hơn. \n\nBạn có thể lý tưởng hóa mọi thứ và thậm chí ngây thơ về động cơ của người khác. Bạn là người dễ gây ấn tượng và dễ hình thành thói quen, có thể bao gồm lạm dụng chất kích thích. Bạn là người kiên nhẫn, nhân ái & lãng mạn. Bạn muốn được thế giới công nhận & bí mật tìm kiếm sự nổi tiếng. \n\nChia sẻ tài năng của mình, giúp đỡ nhân loại, dạy dỗ, tư vấn & chữa lành cho mọi người là những điều nuôi dưỡng tâm hồn bạn. Trong khi theo đuổi mong muốn giải cứu thế giới, hãy đảm bảo bạn không bỏ bê những người thân thiết của mình. Mặt tối tính cách của bạn có thể là tính chiếm hữu, ủ rũ, nhút nhát, ngây thơ & dễ bồn chồn. Là người nghiện mua sắm, bạn rất dễ phung phí tiền bạc.",
  11: "Số này mang thông điệp mạnh mẽ. Là người cực kỳ nhạy cảm, có trực giác và khả năng nhận biết nhạy bén, bạn toát ra vẻ mạnh mẽ, tinh tế và thanh lịch. Bạn sẽ trải nghiệm sự hướng dẫn mang tính tâm linh, và khả năng lãnh đạo bẩm sinh giúp bạn dễ dàng thu hút đồng đội hoặc danh tiếng.\n\nBạn đưa ra quyết định bằng sự kết hợp khó nắm bắt giữa logic, trực giác và cảm xúc. Bạn nhận thức rõ sự khác biệt của bản thân và theo thời gian, bạn sẽ nắm bắt trọn vẹn những món quà đặc biệt của mình để đánh thức và soi sáng cho những người khác.\n\nỞ mặt tối tính cách, bạn có thể bị thao túng và sử dụng quyền lực của mình cho những nỗ lực đáng nghi ngờ về mặt đạo đức. Bạn có thể gặp khó khăn khi phân tách giữa tưởng tượng và thực tế. Bạn thường cảm thấy không ai có thể đáp ứng được kỳ vọng cao của bạn.",
  22: "Bạn có khả năng nhận thức được bức tranh toàn cảnh từ khi còn nhỏ và luôn mơ ước lớn lao. Bạn có rất nhiều khả năng thành công nhất trong tất cả các con số vận mệnh và mong muốn để lại dấu ấn thực sự trên thế giới. Bạn có thể khai thác những khả năng đặc biệt của mình khi trưởng thành, khi bạn thực sự bắt đầu hiểu được khả năng mình được ban cho. Bạn sẽ đạt được những điều lớn lao.\n\nỞ mặt tối tính cách bạn có thể là người ranh mãnh và thâm hiểm trong kinh doanh doanh, phá hoại và thậm chí là xấu xa. Bạn phải luôn sử dụng quyền hạn của mình cho mục đích tốt.",
  33: "Con số vận mệnh 33 mang 1 sứ mệnh to lớn cần phải hoàn thành, nhưng bạn là người có trách nhiệm, vì vậy bạn đã sẵn sang chấp nhận thử thách. Bạn có khả năng sáng tạo vượt trội, khả năng giao tiếp, sự chân thành và lòng trắc ẩn. Phục vụ người khác sẽ tiết lộ khả năng thiên bẩm của bạn. Là người tốt bụng và khiêm tốn, bạn cho đi mà không mong nhận lại. Bạn là người có tầm nhìn xa, tràn đầy niềm vui và lòng trắc ẩn, và bạn dễ dàng có được những mối quan hệ chân thành.\n\nBạn là 1 nhân vật có tầm ảnh hưởng. Số phận của bạn trở thành 1 tấm gương về sức mạnh thực sự của tình yêu và lòng trắc ẩn đối với thế giới. Bạn là một người trợ giúp và 1 người chữa lành.\nMặt tối tính cách của số 33 là tinh thần ‘’tử vì đạo’’, và bạn có thể hay phàn nàn. Bạn thường gánh chịu nỗi đau hoặc vết sẹo của người khác. Bạn sẽ tìm được phần thưởng tuyệt vời cho mình khi sử dụng khả năng chữa lành, an ủi thiên bẩm để giúp đỡ người khác và cung cấp công cụ để mọi người tự giúp mình.",
};

export const SOUL_URGE_SHORT = {
  1: "NGƯỜI THU HÚT NGƯỜI KHÁC",
  2: "NGƯỜI TẬN TÂM NHIỆT TÌNH",
  3: "NGƯỜI CÓ SỨC QUYẾN RŨ",
  4: "NGƯỜI BỘC TRỰC",
  5: "NGƯỜI CÓ TÂM HỒN TỰ DO",
  6: "NGƯỜI YÊU THƯƠNG",
  7: "NGƯỜI BÍ ẨN",
  8: "NGƯỜI PHẤN ĐẤU",
  9: "NGƯỜI CÓ LÒNG BÁC ÁI",
  11: "GỐNG SỐ 2",
  22: "SỐNG SỐ 4",
  33: "GIỐNG SỐ 6",
};

export const SOUL_URGE_TEXT = {
  1: "Với phong cách và hinh ảnh độc đáo, nhóm người có số này sẽ là người dẫn đầu trong các mối quan hệ. Bạn có xu hướng xây dựng những bức tường bảo vệ và có thể có tâm lý :”Tôi sẽ làm tổn thương bạn trước khi bạn có thể thể làm tổn thương tôi’’. Trong sâu thẳm, bạn là một người lãng mạn trong vô vọng. \n\nSự quyến rũ của bạn sẽ đưa bạn đi xa, nhưng bạn mong đợi sẽ tìm thấy điểm tương đồng ở người bạn đời của mình và muốn người khác cũng thông minh và độc lập như bạn. Bạn truyền cảm hứng cho sự đổi mới và không bị thu hút tham gia vào những điều thông thường.",
  2: "Cảm thấy tốn hơn khi ở cùng người khác thay vì 1 mình, những người có con số linh hồn 2 sẽ không độc thân quá lâu. Họ cam kết và mong đợi điều tương tự từ đối phương, đối tượng kết hôn của mình.\nHọ có thể làm bất cứ điều gì cần thiết để giữ hòa khí. Họ là người khéo léo và tốt bụng, có thể nhìn thấy cả 2 mặt của tình huống và thích là người hỗ trợ trong mối quan hệ hơn là người dẫn dắt.\n\nVì cực kỳ nhạy cảm nên những lời chỉ trích có thể gây tổn hại sâu sắc cho họ. Họ cũng là người tận tâm, cống hiến và điều quan trọng nhất là họ cảm thấy được trân trọng.\nVới con số linh hồn 11/2 cảm xúc có thể dao động rất mãnh liệt. Năng lượng gấp đôi số 1 có thể dẫn đến sự ích kỷ. Đảm bảo rằng bạn đang sử dụng khả năng thuyết phục của mình vì 1 mục đích xứng đáng, không phải sự thao túng và lợi ích cá nhân.\nBạn mang lại chất lượng tinh thần sâu sắc cho bất kỳ mối quan hệ nào.",
  3: "Mê hoặc và quyến rũ, con số linh hồn 3 khiến người khác bật cười và cảm thấy họ thật đặc biệt với tính cách nổi bật của họ. Bạn có xu hướng chạy theo những cuộc vui và đấu tranh với tâm lý “cỏ bên kia đồi luôn xanh hơn’’, điều này có thể khiến bạn trở nên thiếu độ tin cậy trong các mối quan hệ.\n\nBạn có thể che giấu cảm xúc thật của mình bằng sự hài hước và nói liên tục. Nếu bạn không vui, người khác sẽ biết được từ lời nói của bạn, điều này có thể giống như những nhát dao, được sử dụng với mục đích làm tổn thương.\n\nBài học của bạn luôn cho người khác sự công nhận mà họ xứng đáng được nhận, không coi mọi thứ là hiển nhiên và mọi người sẽ luôn bên bạn.",
  4: "Con số linh hồn 4 là những người có thể tỏ ra lạnh lùng hoặc xa cách. Cảm xúc dễ biến động và số 4 thích kiểm soát chúng cùng với mọi thứ khác.\nHọ luôn tiếp cận mọi thứ 1 cách thực tế, kể cả tình yêu, và có vẻ là người không lãng mạn lắm.\nHọ có thể tạo ra sự lãng mạn, nhưng cử chỉ hoặc bữa tối lãng mạn đó sẽ được lên kế hoạch và thực hiện 1 cách hoàn hảo. Họ thích cho và nhận những món quà thiết thực hơn là những món quà phù phiếm.\n\nPhẩm chất tốt của họ là bạn đáng tin cậy và sẽ xây dựng 1 cuộc sống có trật tự, hỗ trợ mạnh mẽ cho bạn đời của mình. Họ tìm kiếm 1 tình yêu ổn định với người mà họ tin tưởng để giúp họ xây dựng ước mơ của mình.\nLà người có con số linh hồn 22/4, họ mong muốn để lại 1 di sản cho thế hệ sau. Để hoàn thành sứ mệnh này, họ phải cam kết hết mình với nó.",
  5: "Tự do là yếu tố cần thiết cho hạnh phúc của con số linh hồn 5. Với niềm đam mê sâu sắc đối với sự thay đổi, du lịch và phiêu lưu, bạn tìm kiếm cảm giác không bị gò bó, giới hạn trong các mối quan hệ. Nhóm này khó giữ lời hứa và cũng không tuân thủ tốt các yêu cầu mệnh lệnh.\n\nSố 5 thường bị chi phối bởi các giác quan nên quan hệ tình dục là điều đặc biệt quan trọng với nhóm này. Bạn luôn muốn sự đa dạng và điều đó mở rộng đến cả phòng ngủ. Những thú vui cảm xúc mang đến cho bạn niềm hạnh phúc nhưng cũng có thể dẫn đến sự vô độ và lạm dụng.\nCon số linh hồn 5 thường có xu hướng kết hôn muộn hơn. Họ chống lại những ràng buộc tình cảm và những cam kết lâu dài.",
  6: "Mong muốn lớn nhất của những người có con số linh hồn 6 là yêu và được yêu. Đa cảm, kiên nhẫn, từ bi và thấu hiểu, bạn là người bạn đời tuyệt vời và khiến tình yêu trở nên không quá phức tạp.\n\nSố 6 có xu hướng lý tưởng hóa tình yêu, tạo ra hình ảnh về 1 cuộc sống tươi đẹp và hoàn hảo, sau đó phấn đấu vì nó. Bạn mong đợi sự cam kết trong các mối quan hệ. Số 6 cần cảm thấy được phụ thuộc, thích lắng nghe và đưa ra lời khuyên, hỗ trợ.\n\nVới tình yêu sâu sắc dành cho tổ ấm của mình, số 6 thường chọn có con, dĩ nhiên không phải lúc nào cũng có thể như vậy. Người có con số linh hồn 33/6 muốn dấy lên sự rung động tình yêu của thế giới. Bạn là người giàu cảm xúc và muốn mang lại sự hiểu biết cho thế giới thông qua tình yêu.",
  7: "Sự thông minh là điểm quyến rũ và nét tinh tế của bạn. Bạn tạo cho người khác ấn tượng rằng bạn thích giữ mọi thứ riêng tư. Con số linh hồn này có thể chọn 1 cuộc sống cô độc, quan tâm đến việc của bản thân hơn là của người khác. Nếu bạn yêu đương hay kết hôn, đó sẽ là khi bạn đã trưởng thành và đó phải là một mối quan hệ rất riêng tư và an toàn. Bạn cảm thấy việc trở thành nhà sư hoặc thầy tu là 1 ý tưởng hấp dẫn.\n\nBạn thích nói về sự thật hơn là cảm giác và cảm xúc không thể đoán trước. Cách tiếp cận khách quan của bạn đối với các mối quan hệ lãng mạn có thể gây ra sự ngờ vực, vì người kia có thể cảm thấy rằng bạn đang từ chối họ. Trở nên dễ bị tổn thương về mặt cảm xúc và tạo dựng những kết nối sâu sắc là điều nằm ngoài vùng an toàn của bạn nhưng cần thiết cho 1 cuộc sống viên mãn.",
  8: "Số 8 thích học từ khó khăn và các vấn đề của trái tim cũng không ngoại lệ. Bạn có thể thấy mình đang ở trong những mối quan hệ cùng với một kiểu người nhiều lần. Điều này có thể gây kiệt quệ về mặt cảm xúc và tài chính. Hãy cố tìm ra hình mẫu lãng mạn của bạn và chấm dứt vòng theo đuổi luẩn quẩn.\n\nSố 8 được hưởng tiện nghi, vật chất và giàu sang. Điều quan trọng đối với bạn là người khác cảm nhận bạn là người thành công. Bạn có ước mơ lớn và không ngại vất vả. Bạn cần được thử thách (và phần thưởng cho việc vượt qua thử thách), ngay cả trong các mối quan hệ, nếu không bạn sẽ rơi vào trạng thái rung động thấp, trở nên tàn bạo, độc ác, chán nản và thất vọng. Người bạn đời lý tưởng của bạn phải hấp dẫn, có năng lực và được định hướng như bạn.\n\nCho dù có chủ ý hay không số này có xu hướng kết hôn hoặc kết đôi với người có nguồn lực có thể hỗ trợ tầm nhìn và nhu cầu thành công về mặt chất của bạn. \nHãy nhớ rằng không có chỗ cho đạo đức giả trong tình yêu, hãy đối xử với đối phương của bạn như cách bạn muốn được đối xử.",
  9: "Là những người mong muốn tình yêu phổ quát và thực sự quan tâm đến hạnh phúc của nhân loại. Là những linh hồn già dặn, số 9 khôn ngoan và có tài năng với trực giác đặc biệt.\n\nHọ là người chu đáo và luôn đoán trước được nhu cầu của người bạn đời, đối xử với họ như vua hoặc hoàng hậu. Trong mối quan hệ với số 9, bạn thường sẽ nhận thấy sự chênh lệch tuổi tác đáng kể.\n\nSố 9 thầm mơ ước có ảnh hưởng lớn đến thế giới và thậm chí có thể trở nên nổi tiếng, mặc dù bạn sở hữu vẻ đẹp của sự khiêm tốn, Vì hiểu biết và rộng lượng nên bạn thường bị giằng xé giữa nhu cầu của bản thân và nhu cầu của người khác.\n\nSống cảm xúc và nhạy cảm, bạn cũng có thể hay chỉ trích và thất thường. Bạn sẽ thất vọng khi mọi người không thể đáp ứng kỳ vọng cao của bạn hoặc không thể tự giúp đỡ chính mình khi có cơ hội.",
  11: "Cảm thấy tốn hơn khi ở cùng người khác thay vì 1 mình, những người có con số linh hồn 2 sẽ không độc thân quá lâu. Họ cam kết và mong đợi điều tương tự từ đối phương, đối tượng kết hôn của mình.\n\nHọ có thể làm bất cứ điều gì cần thiết để giữ hòa khí. Họ là người khéo léo và tốt bụng, có thể nhìn thấy cả 2 mặt của tình huống và thích là người hỗ trợ trong mối quan hệ hơn là người dẫn dắt.\n\nVì cực kỳ nhạy cảm nên những lời chỉ trích có thể gây tổn hại sâu sắc cho họ. Họ cũng là người tận tâm, cống hiến và điều quan trọng nhất là họ cảm thấy được trân trọng.\n\nVới con số linh hồn 11/2 cảm xúc có thể dao động rất mãnh liệt. Năng lượng gấp đôi số 1 có thể dẫn đến sự ích kỷ. Đảm bảo rằng bạn đang sử dụng khả năng thuyết phục của mình vì 1 mục đích xứng đáng, không phải sự thao túng và lợi ích cá nhân.\n\nBạn mang lại chất lượng tinh thần sâu sắc cho bất kỳ mối quan hệ nào.",
  22: "Con số linh hồn 22/4 là những người có thể tỏ ra lạnh lùng hoặc xa cách. Cảm xúc dễ biến động và số 4 thích kiểm soát chúng cùng với mọi thứ khác.\nHọ luôn tiếp cận mọi thứ 1 cách thực tế, kể cả tình yêu, và có vẻ là người không lãng mạn lắm.\n\nHọ có thể tạo ra sự lãng mạn, nhưng cử chỉ hoặc bữa tối lãng mạn đó sẽ được lên kế hoạch và thực hiện 1 cách hoàn hảo. Họ thích cho và nhận những món quà thiết thực hơn là những món quà phù phiếm.\n\nPhẩm chất tốt của họ là bạn đáng tin cậy và sẽ xây dựng 1 cuộc sống có trật tự, hỗ trợ mạnh mẽ cho bạn đời của mình. Họ tìm kiếm 1 tình yêu ổn định với người mà họ tin tưởng để giúp họ xây dựng ước mơ của mình.\n\nLà người có con số linh hồn 22/4, họ mong muốn để lại 1 di sản cho thế hệ sau. Để hoàn thành sứ mệnh này, họ phải cam kết hết mình với nó.",
  33: "Mong muốn lớn nhất của những người có con số linh hồn 33/6 là yêu và được yêu. Đa cảm, kiên nhẫn, từ bi và thấu hiểu, bạn là người bạn đời tuyệt vời và khiến tình yêu trở nên không quá phức tạp.\n\nSố 6 có xu hướng lý tưởng hóa tình yêu, tạo ra hình ảnh về 1 cuộc sống tươi đẹp và hoàn hảo, sau đó phấn đấu vì nó. Bạn mong đợi sự cam kết trong các mối quan hệ. Số 6 cần cảm thấy được phụ thuộc, thích lắng nghe và đưa ra lời khuyên, hỗ trợ.\n\nVới tình yêu sâu sắc dành cho tổ ấm của mình, số 6 thường chọn có con, dĩ nhiên không phải lúc nào cũng có thể như vậy. Người có con số linh hồn 33/6 muốn dấy  lên sự rung động tình yêu của thế giới. Bạn là người giàu cảm xúc và muốn mang lại sự hiểu biết cho thế giới thông qua tình yêu.",
};

export const PERSONALITY_SHORT = {
  1: "NĂNG ĐỘNG VÀ HIỆU QUẢ",
  2: "THÂN THIỆN VÀ KHIÊM TỐN",
  3: "TRUYỀN CẢM HỨNG VÀ THU HÚT",
  4: "ĐÁNG TIN CẬY VÀ NHẤT QUÁN",
  5: "NỔI BẬT VÀ DÍ DỎM",
  6: "THẤU HIỂU VÀ ĐỒNG CẢM",
  7: "NGHIÊM TÚC VÀ BÍ ẨN",
  8: "MẠNH MẼ VÀ ẤN TƯỢNG",
  9: "ẤN TƯỢNG VÀ CÁ TÍNH",
  11: "GIỐNG SỐ 2",
  22: "GIỐNG SỐ 4",
  33: "THẤU HIỂU VÀ ĐỒNG CẢM",
};

export const PERSONALITY_TEXT = {
  1: "Có  phong cách, vui vẻ, thích kiểm soát, có khả năng, thống trị, hung hăng, không nhạy cảm, đáng sợ, can đảm.",
  2: "Hợp tác, khiêm tốn, ngoại giao tốt, lễ độ, một người biết lắng nghe, nhút nhát, tinh tế, thường bị coi nhẹ..",
  3: "Hấp dẫn, tích cực, thu hút, hướng ngoại, lạc quan, dễ nói chuyện, vui vẻ, tình cảm, dễ bị phân tán, xuề xòa.",
  4: "Có vẻ ngoài thực tế, đáng kính, bảo thủ, đáng tin cậy, có trách nhiệm, dè dặt, không linh hoạt, tự cao tự đại.",
  5: "Vui vẻ, cầu tiến, lạc quan, hào hứng với mọi thứ, hấp dẫn, hướng ngoại, hào sảng, thu hút, ngoại hình trẻ trung, thiếu trách nhiệm.",
  6: "Hay bảo vệ người khác, đáng tin cậy, tháo vát, thanh lịch, cầu toàn, thông cảm, có năng lực, có kỹ năng chăm sóc, trang nhã.",
  7: "Có nhận thức, quan sát tốt, thông minh, đàng hoàng, dè dặt, nội tâm, hướng nội, hay triết lý, lập dị, xa xách.",
  8: "Có ảnh hưởng, quyền lực, tham vọng, có thẩm quyền, có đầu óc kinh doanh, có tầm nhìn xa, tự tin, tinh tế, tàn nhẫn, tham lam, tự phụ, thích kiểm soát.",
  9: "Có năng lực, cương quyết, trung thực, ổn định, sáng tạo, thành thạo, hiệu quả, ngoại giao tốt, kiêu ngạo, đáng sợ, hay ghen tị.",
  11: "Hợp tác, khiêm tốn, ngoại giao tốt, lễ độ, một người biết lắng nghe, nhút nhát, tinh tế, thường bị coi nhẹ.",
  22: "Có vẻ ngoài thực tế, đáng kính, bảo thủ, đáng tin cậy, có trách nhiệm, dè dặt, không linh hoạt, tự cao tự đại..",
  33: "(Giống số 6) Hay bảo vệ người khác, đáng tin cậy, tháo vát, thanh lịch, cầu toàn, thông cảm, có năng lực, có kỹ năng chăm sóc, trang nhã.",
};

export const BIRTHDAY_TEXT = {
  1: "Bạn là người độc lập, thích cạnh tranh và là 1 nhà lãnh đạo bẩm sinh. \n\nBạn là người sáng tạo với nhiều ý tưởng độc đáo và bạn thích nổi bật. Bạn chủ động và có thể khuấy động, tạo cảm hứng cho mọi người. \n\nBạn cũng có thể cứng đầu, ích kỷ và thất thường. Bài học tuyệt vời của bạn là học về ranh giới, chia sẻ và làm việc theo nhóm.",
  2: "Tốt bụng, kiên nhẫn, nhạy cảm và trực giác nhạy bén, bạn làm việc theo cặp tốt hơn là một mình. \n\nBạn là một đồng đội hòa đồng, chu đáo và luôn hỗ trợ người  khác. Bạn không khao khát ánh đèn sân khấu. \n\nBài học cho bạn là học cách đứng lên vì chính mình.",
  3: "Bạn là người thân thiện và tràn đầy năng lượng, và khả năng sáng tạo của bạn không có giới hạn. \n\nBạn là người rất thân thiện, hòa đồng, vui vẻ và  là người thích cuộc sống của những bữa tiệc. \n\nBài học của bạn là học cách quản lý cảm xúc và ngừng tìm kiếm sự thỏa mãn tức thì.",
  4: "Bạn thực tế, đáng tin cậy, chăm chỉ, trung thực và công bằng. \n\nBạn là người có tổ chức và hành động nhanh chóng. Bạn thích lập kế hoạch và luôn muốn biết những gì sẽ xảy ra. \n\nBài học của bạn là học cách giải phóng quyền kiểm soát. Nếu sinh ngày 13 sẽ khuyến khích bạn đấu tranh với sự trì hoãn.",
  5: "Bạn thôi thúc bởi lời kêu gọi của cảm giác phiêu lưu và sự buồn chán là điểm yếu của bạn. \n\nCuộc sống phải luôn thú vị hoặc bạn sẽ thoát ra và bước tiếp. Bạn là người tháo vát, dám chấp nhận sự thay đổi, và đôi khi bốc đồng. \n\nBài học của bạn là học cách chịu trách nhiệm.",
  6: "Bạn có trách nhiệm và hướng về gia đình. Bạn cũng yêu động vật. \n\nTrung thành, cầu toàn và chu đáo đều là 1 phần bản chất của bạn (mặc dù bạn có xu hướng can thiệp vào những công việc không phải của mình). \n\nBạn sẽ học được cách vượt qua sự phản bội và chỉ quan tâm đến việc của bản thân mình.",
  7: "Bạn tập trung quá nhiều vào phân tích mọi thứ, cố gắng tìm ra ý nghĩa sâu sắc trong tất cả những gì bạn làm. Bạn thích đọc và ham mê học hỏi. Bạn luôn đặt ra các giả thuyết. \n\nBạn vừa tò mò vừa đòi hỏi sự riêng tư. Bài học của bạn là học cách làm việc với người khác 1 cách vị tha.",
  8: "Thành công là điều quan trọng và có thể đạt được với bạn. Bạn thích xe đẹp, đồ hiệu và bất cứ thứ gì có tên tuổi. \n\nBài học của bạn là tìm sự cân bằng giữa tinh thần và vật chất, đồng thời học tính kiên nhẫn và lòng trung thành. Không phải lúc nào bạn cũng phải trải qua khó khăn để học hỏi.",
  9: "Bạn hào phóng, sáng tạo, nhạy cảm, khoan dung, cởi mở và có cách tiếp cận độc đáo để giải quyết vấn đề. \n\nBạn là người có tấm lòng nhân ái với mong muốn làm cho thế giới trở nên tốt đẹp hơn. \n\nHãy cẩn thận với việc tỏ ra biết tất cả hoặc ra vẻ trịch thượng. Bài học cho bạn là học cách tha thứ và buông bỏ.",
  11: "Bạn sở hữu nhiều tài năng thiên bẩm. Bạn tốt bụng và là người điều tiết bầu không khí chung. \n\nBạn có khả năng phát hiện xu hướng và vượt qua ranh giới. Bạn cũng có thể bị lôi kéo và trở nên cực đoan. Bài học cho bạn là học tính quyết đoán và không từ bỏ ước mơ của mình.",
  22: "Bạn là 1 nhà xây dựng thành thạo, Nhiều công trình hoành tráng lần đầu tiên được hoàn thành bởi nhưng người có con số ngày sinh này. \n\nBạn có thể là người trẻ nhất hoặc người đầu tiên đạt được 1 cột mốc quan trọng. Bạn suy nghĩ hướng ngoại và có tầm nhìn thực sự. \n\nBạn là người mạnh mẽ và luôn tiềm ẩn nguy cơ lạm dụng sức mạnh này. Bài học của bạn sẽ liên quan đến cái tôi.",
  33: "(Giống số 6) Bạn có trách nhiệm và hướng về gia đình. Bạn cũng yêu động vật. \n\nTrung thành, cầu toàn và chu đáo đều là 1 phần bản chất của bạn (mặc dù bạn có xu hướng can thiệp vào những công việc không phải của mình). \n\nBạn sẽ học được cách vượt qua sự phản bội và chỉ quan tâm đến việc của bản thân mình.",
};

export const ATTITUDE_TEXT = {
  1: "Bạn là người độc đáo: Bạn mang dấu ấn cá nhân của riêng mình vào mọi việc bạn làm. \n\nBạn có thể tỏ ra hung hăng nhưng đồng thời rất tự tin và có năng lực. \n\nBạn tràn đầy nhiệt huyết và những ý tưởng tuyệt vời. Bạn không sợ đối đầu, có thể rất bốc đồng và không phải lúc nào cũng xem xét hậu quả lâu dài của các hành động và quyết định của mình.",
  2: "Ấn tượng đầu tiên của người khác về bạn là một người tử tế, ngoại giao tốt và kiên nhẫn. \n\nSự nhạy cảm đáng kinh ngạc của bạn thường được thể hiện dưới dạng những lo lắng. \n\nHãy cẩn trọng về những gì bạn ''nhận' từ người khác. Bạn không cần phải sở hữu những trải nghiệm, tâm trạng, ý kiến hoặc cảm xúc của người khác.",
  3: "Bạn có vẻ ngoài vui vẻ và vô tư, nhưng rất nhạy cảm và thầm sợ bị chỉ trích và phản đối. Bạn có thể bị phân tán, thường kể nhiều câu chuyện cùng một lúc. \n\nBạn thích cười và làm cho người khác cười. Bạn cực kỳ giỏi ngoại giao, thông minh và hóm hỉnh. \n\nBạn có vẻ khá thất thường và khó tính với bản thân. Đừng gò ép bản thân với đống cảm xúc hỗn loạn đó: Hãy vượt qua nó và đừng nhìn nhận mọi thứ một cách cá nhân thái quá.",
  4: "Về mặt tình cảm, hãy cẩn thận với vẻ ngoài có vẻ bất cần hoặc lạnh lùng. \n\nViệc thể hiện sự dễ bị tổn thương về mặt cảm xúc không phải lúc nào cũng là điểm yếu. \n\nBạn yêu thích các quy tắc, sự công bằng và mọi thứ phải công bằng. Bạn trân trọng việc người khác đánh giá cao kỹ năng tổ chức và quản lý của bạn.",
  5: "Bạn sử dụng sức hút của mình để điều hướng và đạt được những gì bạn muốn trong cuộc sống. \n\nBạn thích cuộc sống phiêu lưu, thú vị với nhịp sống nhanh, bạn dường như không sợ gì và luôn tìm kiếm sự nhanh chóng, đôi khi vội vàng. \n\nBạn hoạt động tốt nhất trong môi trường luôn thay đổi, năng động và thậm chí hỗn loạn. Người khác sẽ chú ý đến việc bạn không thỏa hiệp với sự buồn chán.",
  6: "Có năng lực, thông minh và nhanh trí, bạn rất giỏi trong trường hợp khẩn cấp và thậm chí còn giỏi hơn trong việc kiểm soát câu chuyện. \n\nNhư 1 bác sĩ giỏi, bạn biết phải làm gì và gọi cho ai. Những người khác nhìn nhận bạn là một người cầu toàn với gu thẩm mỹ tuyệt vời, luôn tìm cách đặt cái nhìn hoàn hảo của mình vào mọi thứ.",
  7: "Bạn cảm thấy những câu chuyện phiếm có thể giết chết mình: Nếu việc trò chuyện bao gồm những tiếng cười giả tạo, bạn thà ở nhà. Điều này khiến bạn có vẻ lạc lõng và xa cách. Dường như có 1 bầu không khí bí ẩn về bạn vì bạn thích giữ chặt các lá bài của mình. Bạn muốn quan sát và đặt câu hỏi hơn là chia sẻ bất cứ điều gì quá riêng tư.\n\nHam học hỏi, bạn thích những cuộc trò chuyện có nội dung và riêng tư hơn là những cuộc trò chuyện vui vẻ theo nhóm. Những lời châm biếm và đôi khi là khiếu hài hước khô khan của bạn không phải lúc nào cũng được đón nhận. Mọi người thấy bạn hấp dẫn nhưng khó nắm bắt.",
  8: "Sinh ra để dẫn đầu, và khi được cân bằng, không gì có thể ngăn cản sự phát triển của số này. Với khao khát được cống hiến, bạn có ước mơ, hoài bão lớn, điều này thường khiến bạn bị thất vọng. Bạn thể hiện sự tự tin và nỗ lực để duy trì một hình ảnh thành công.\n\nĐôi khi không khéo léo và cố chấp, bạn coi thường những thứ lãng phí thời gian. Suy cho cùng thì thời gian là tiền bạc, và nó có thể mang lại sự ổn định, an toàn và tự do mà bạn mong muốn. Nếu thấy mình thiếu nguồn lực hoặc thiếu khả năng kiểm soát, bạn có thể thể hiện thái độ chống đối và tức giận. Bạn sẽ nhanh chóng phải nhận Nghiệp, dù tốt hay xấu.",
  9: "Bạn có vẻ tự tin và sự quyến rũ để tận dụng. Mọi người thường có cảm giác bị đe dọa bởi bạn. Thái độ của số 9 có thể phân cực, mọi người sẽ yêu quý bạn hoặc coi thường bạn. Bất kỳ ai có điều gì đó muốn che giấu đều lo sợ bạn sẽ phơi bày chúng trong vô thức.",
  11: "Ấn tượng đầu tiên của người khác về bạn là một người tử tế, ngoại giao tốt và kiên nhẫn. Sự nhạy cảm đáng kinh ngạc của bạn thường được thể hiện dưới dạng những lo lắng. Hãy cẩn trọng về những gì bạn ''nhận'' từ người khác. Bạn không cần phải sở hữu những trải nghiệm, tâm trạng, ý kiến hoặc cảm xúc của người khác. Số 11 có thêm trực giác mãnh liệt và thậm chí nhạy cảm hơn với những đặc điểm tính cách của số 2. Bạn ở trạng thái tốt nhất khi truyền cảm hứng cho người khác.",
  22: "Về mặt tình cảm, hãy cẩn thận với vẻ ngoài có vẻ bất cần hoặc lạnh lùng. Việc thể hiện sự dễ bị tổn thương về mặt cảm xúc không phải lúc nào cũng là điểm yếu. Bạn yêu thích các quy tắc, sự công bằng và mọi thứ phải công bằng. Bạn trân trọng việc người khác đánh giá cao kỹ năng tổ chức và quản lý của bạn.\n\nCon số vua 22 có năng lượng của số 4 và cũng được nâng cấp thành người kiến tạo tài ba của số 22. Những người khác sẽ thấy khả năng tuyệt vời của bạn trong việc xây dựng thứ gì đó có giá trị lâu dài. Kiểm soát cái tôi của bạn: Bạn có thể tỏ ra tự thu mình.",
  33: "Giống số 6. Có năng lực, thông minh và nhanh trí, bạn rất giỏi trong trường hợp khẩn cấp và thậm chí còn giỏi hơn trong việc kiểm soát câu chuyện. Như một bác sĩ giỏi, bạn biết phải làm gì và gọi cho ai. Những người khác nhìn nhận bạn là một người cầu toàn với gu thẩm mỹ tuyệt vời, luôn tìm cách đặt cái nhìn hoàn hảo của mình vào mọi thứ.",
};

export const PERSONAL_MONTH_TEXT = {
  1: "Hãy bắt đầu! Bắt đầu một cái gì đó mới.",
  2: "Trọng tâm của tháng này sẽ là các mối quan hệ. Hãy hợp tác và kiên nhẫn.",
  3: "Tháng này xảy ra 1 sự kiện quan trọng với bạn. Hãy thoải mái giao lưu, vui chơi và tìm cách giải tỏa thật sáng tạo. Cảm xúc của bạn sẽ tăng cao.",
  4: "Đừng trì hoãn! Hãy quan tâm đến chi tiết và bất kỳ điều gì bạn chưa hoàn thiện. Luôn quan tâm đến sức khỏe của bạn.",
  5: "Tránh buôn chuyện hay hóng hớt chuyện phiếm. Đón nhận và nắm bắt sự thay đổi. Bạn có thể vụng về và dễ va chạm trong tháng này.",
  6: "Làm đẹp môi trường xung quanh bạn. Tập trung vào gia đình và vật nuôi.",
  7: "Trở thành chuyên gia 1 lĩnh vực nào đó. Dành thời gian tra cứu và học hỏi. Chăm sóc bản thân là điều quan trọng lúc này. Bạn có thể cảm thấy tách biệt và ẩn dật.",
  8: "Tháng này mang đến vòng xoay tiền bạc. Có thể có 1 khoản tiền thưởng hoặc các khoản tiền bất ngờ đến với bạn. Hãy coi chừng, nó sẽ nhanh chóng rời đi do phát sinh những chi phí không lường trước được.",
  9: "Tha thứ, loại bỏ mọi thứ, cho đi thời gian và tiền bạc của bạn và thực hiện những việc làm tử tế bất kỳ. Đón nhận phần thưởng của bạn! Và chuẩn bị cho chu kỳ 9 tháng tiếp theo.",
  11: "(Giống số 2) Trọng tâm của tháng này sẽ là các mối quan hệ. Hãy hợp tác và kiên nhẫn.",
  22: "(Giống số 4) Đừng trì hoãn! Hãy quan tâm đến chi tiết và bất kỳ điều gì bạn chưa hoàn thiện. Luôn quan tâm đến sức khỏe của bạn.",
  33: "(Giống số 6) Làm đẹp môi trường xung quanh bạn. Tập trung vào gia đình và vật nuôi.",
};

export const MATURITY_TEXT = {
  1: "Bạn cần có sự độc lập và tính cá nhân mạnh mẽ hơn và phải nỗ lực nhiều hơn để được công nhận và đền đáp. Cẩn trọng để không trở thành kẻ bắt nạt và gây chiến.",
  2: "Sự nhạy cảm cũng như sự khôn khéo và khả năng ngoại giao của bạn sẽ tăng lên. Bạn phù hợp với những công việc phía sau hậu trường, lựa chọn hướng dẫn nhẹ nhàng thay vì sử dụng vũ lực.",
  3: "Bạn sẽ trở nên hòa đồng và hướng ngoại hơn. Khả năng giao tiếp của bạn được cải thiện cùng sự nổi tiếng và tiềm năng sáng tạo của bạn. Bạn có thể vẽ tranh, viết lách hoặc diễn xuất.",
  4: "Bạn sẽ thấy mình trở thành người có kế hoạch, thực tế và có tổ chức hơn. Tránh việc quá cứng nhắc, không linh hoạt và cố chấp. Hãy nhớ dành thời gian để tận hưởng niềm vui.",
  5: "Du lịch, tự do và những sự kiện bất ngờ sẽ chi phối nửa sau cuộc đời bạn. Khả năng kể chuyện của bạn sẽ phát triển, và bạn sẽ trở nên độc đáo và thú vị hơn, dám chấp nhận rủi ro hơn. Hãy cẩn thận với việc phân tán năng lượng của bạn.",
  6: "Gia đình, bạn bè và cộng đồng sẽ ngày càng quan tâm đến bạn. Bạn sẽ trưởng thành như một nhà hiền triết thông thái và có thể đưa ra lời khuyên cũng như sự an ủi cho những ai cần nó. Con số trưởng thành này hứa hẹn một tuổi già an toàn. Đây thường là những người con chăm sóc cha mẹ già.",
  7: "Bạn phải đề phòng việc trở nên ẩn dật. Bạn sẽ dành thời gian để đọc và tiếp tục rèn luyện bản thân trong khi đặt ra những câu hỏi lớn trong cuộc sống. Trực giác của bạn sẽ phát triển mạnh mẽ hơn cũng như khả năng hình thành các ý kiến và kết luận độc đáo của bạn cũng được tăng cường.",
  8: "Bạn sẽ học cách tách khỏi thành công vật chất. Nhiều người với con số trưởng thành này không bao giờ thực sự nghỉ hưu, và ngày càng bị sự tích lũy và lòng tham chi phối. Bạn có thể đạt được thành công và sự độc lập tài chính nếu kiểm soát được cái tôi của mình và tập trung vào các hành động nhân đạo để duy trì sự cân bằng.",
  9: "Trí tuệ, khiếu hài hước và tấm lòng nhân đạo của bạn đều sẽ phát triển. Hoạt động tình nguyện và mối quan tâm đến nghệ thuật và văn hóa sẽ mang lại niềm vui cho bạn. Bạn sẽ cố gắng đóng góp những điều có giá trị lâu dài.",
  11: "Số 11 sẽ có thêm những trải nghiệm trực giác và tâm linh đáng kinh ngạc khi già đi. Hãy tin vào cảm nhận của bạn. Sự nhạy cảm và khả năng phán đoán tính cách của bạn sẽ ngày càng sâu sắc. Bạn sẽ phân biệt đối xử rõ với những người mà bạn cho phép bước vào thế giới của mình và kết quả là những mối quan hệ lâu dài.",
  22: "Bạn sẽ có 1 nền tảng vững chắc, trực giác nhạy bén, sự tự tin mới hình thành và sức mạnh cá nhân sâu sắc. Những công cụ này sẽ giúp bạn biến nhiều ước mơ thành hiện thực và để lại di sản.",
  33: "Bạn làm mọi việc với sự tận tâm. Bây giờ bạn có thể mang tầm nhìn của mình vào cuộc sống với lòng trắc ẩn, tập trung năng lượng cảm xúc của bạn vào mục tiêu cao hơn và phù hợp với những hiểu biết tâm linh. Con số trưởng thành của bạn là 1 cái gì đó để nắm bắt và đang mong đợi. Bạn đang hợp nhất đường đời và vận mệnh của mình thành tổng thể kinh nghiệm và trí tuệ tối thượng. Bây giờ bạn có thể tự tin định hướng cuộc sống của mình và cuối cùng là thực hiện ước mơ.",
};

export const PERSONAL_YEAR_SHORT = {
  1: "NĂM KHỞI ĐẦU",
  2: "MỐI QUAN HỆ & SỰ NHẪN NẠI",
  3: "CÁC SỰ KIỆN XÃ HỘI VÀ CẢM XÚC",
  4: "KỶ LUẬT VÀ CHI TIẾT",
  5: "SỰ THAY ĐỔI TỰ DO & ĐỔI MỚI",
  6: "GIA ĐÌNH & TRÁCH NHIỆM",
  7: "CHUYÊN MÔN & TỰ CHĂM SÓC BẢN THÂN",
  8: "THÀNH ĐẠT QUYỀN LỰC & TIỀN BẠC",
  9: "HOÀN THIỆN & GIẢI PHÓNG",
  11: "GIỐNG SỐ 2",
  22: "GIỐNG SỐ 4",
  33: "GIA ĐÌNH & TRÁCH NHIỆM",
};

export const PERSONAL_YEAR_TEXT = {
  1: "Đây là lúc tiến về phía trước! Đó là một sự thay đổi đáng hoan nghênh sau năm 9 của bạn khi bạn đang dần buông bỏ và nhường chỗ cho những khởi đầu mới. Với hiệu ừng hào quang, bạn vẫn sẽ cảm thấy có một vài thứ rơi rớt mà bạn đã bỏ qua để ''tiễn biệt'' năm cũ. \n\nBạn có thể thấy năm 1 là một khởi đầu chậm chạp. Nhưng đây chính là thời điểm hoàn hảo để bạn đặt ra dự định, gieo hạt, phát triển ý tưởng và bắt đầu hành động để biến chúng thành hiện thực. Những gì xảy ra bây giờ sẽ ảnh hưởng trực tiếp đến phần thưởng hoặc thành quả của bạn trong chín năm tới.\n\nBạn có thêm sự tự tin mới. Bạn có động lực và thực sự có thể làm mọi thứ xảy ra. Năm này sẽ là năm của chuyển động, tiến bộ và sẽ trôi qua nhanh chóng. Bạn có thể thấy mình quyết liệt, tích cực hơn hiện tại. Hãy nhớ giữ mối quan hệ tốt với những người khác, đừng cứng đầu và hãy chủ động yêu cầu giúp đỡ khi cần.",
  2: "Năm này là thời gian để nuôi dưỡng những hạt giống bạn đã gieo mầm vào năm 1. Thời gian của bạn sẽ được sử dụng tốt để chăm sóc những ý tưởng lớn mà bạn đã đề ra vào năm trước.\n\nBạn sẽ có những kết nối mạnh mẽ và gặp gỡ những người có thể giúp bạn đạt được mục tiêu và ước mơ của mình. Đây là thời điểm tuyệt vời cho những mối quan hệ lãng mạn và xây dựng gia đình.\n\nNăm này diễn biến chậm hơn 1 chút so với năm trước, và sự kiên nhẫn và khă năng thỏa hiệp của bạn sẽ được thử thách. Bạn cũng sẽ trải qua những việc liên quan đến sự nhạy cảm.",
  3: "Năm cá nhân 3 của bạn sẽ là 1 năm của các hoạt động và sự kiện xã hội, và bạn có thể thấy mình nổi tiếng hơn bình thường. Đây là năm của những kết nối tuyệt vời: Hãy sẵn sàng đón nhận những lời mời. Vũ trụ muốn tạo 1 số kết nối cho bạn trong năm nay! Hãy để chúng xảy ra. Chấp nhận mọi lời mời bạn nhận được và gặp gỡ nhiều người nhất có thể.\n\nĐây cũng sẽ là 1 năm đầy cảm xúc, và điều này có nghĩa là bạn sẽ trải nghiệm mọi cung bậc cảm xúc: tức giận, sợ hãi, buồn bã, vui vẻ, thất vọng...Tìm một lối thoát sáng tạo mà bạn có thể chuyển hướng nguồn cảm xúc đang dâng cao của mình. Khả năng sáng tạo và kỹ năng giao tiếp của bạn sẽ đạt đến đỉnh cao trong năm nay.\n\nĐây cũng là thời điểm định mệnh! Trong năm 3, bạn có thể sẽ gặp một người có ảnh hưởng lớn đến cuộc sống của bạn hoặc mang lại cho bạn cơ hội thay đổi cuộc đời.\n\nNhững người có năm cá nhân này yêu thích sự tăng trưởng và mở rộng. Hãy thận trọng, đừng phóng đại và tô điểm quá nhiều. Bạn cũng cần chú ý đến việc tăng cân.",
  4: "Hãy tập trung và tận tâm: Điều này yêu cầu việc chú tâm vào chi tiết, hiểu sự trì hoãn và tuân theo các quy tắc. Nếu phá vỡ các quy tắc, bạn sẽ phải gánh chịu hậu quả. Nếu tăng tốc, bạn sẽ đuổi kịp, nếu nói dối, bạn sẽ bị lộ. Hãy cẩn thận đừng bỏ bê sức khỏe của mình. Hãy kiểm tra sức khỏe định kỳ.\n\nThông điệp của năm này là về sự buông bỏ và học cách tin tưởng vào cảm nhận thiên tính. Hãy tuân theo tự nhiên và đừng ép buộc thứ gì, nếu không chúng sẽ phản tác dụng, một cách tệ hại!",
  5: "Bạn có thể bắt đầu cảm thấy bị giam cầm và sẵn sàng thay đổi. Đây là thời điểm giữa chu kỳ và bạn có thể cảm thấy ''ngứa ngáy'', mong muốn điều gì đó mới mẻ. Năm này, thường bạn sẽ muốn mua nhà mới, đổi xe, chuyển việc hoặc những thứ quan trọng khác. Năm 5 cũng là năm cho các mối quan hệ xã hội là thời điểm tốt để bắt đầu một mối quan hệ yêu đương mới. Đây cũng là 1 năm tuyệt vời để đi du lịch, tham gia 1 cuộc phiêu lưu và trải nghiệm những điều mới. Hãy đặc biệt chú ý đến những người mới và những cơ hội mới đến với bạn.\n\nHãy chú ý cẩn thận khi tham gia bàn tán và buôn chuyện trong năm này - bạn sẽ thu hút họ như một thỏi nam châm! Bạn cũng có thể thấy mình hơi vụng về hoặc dễ gặp tai nạn.",
  6: "Năm cá nhân 6 của bạn kiểm soát quan hệ hôn nhân, việc sinh con hay liên quan đến cái chết, gia đình, nhà cửa và thậm chí cả vật nuôi của bạn. Bản chất ma quỷ/thiên thần của số 6 cũng áp dụng cho năm này.\n\nNăm 6 cũng kiểm soát việc học hành, vì vậy bạn có thể thấy mình quay trở lại trường học hoặc tham gia các lớp học hoặc hội thảo vào cuối tuần. Đây là 1 năm tuyệt vời để học được điều gì đó mới. Từ tính cá nhân của bạn rất mạnh trong năm nay, vì vậy đây có thể là một năm thành công của mối quan hệ lãng mạn và chinh phục.\n\nBạn có thể thấy một vài điều tốt nhất và một vài sự kiện khó khăn nhất về mặt cảm xúc trong cuộc đời bạn sẽ xảy ra trong năm 6. Bạn có thể  kết hôn, và vài tháng sau, mất một vài người thân hoặc thú cưng.",
  7: "Năm này là thời điểm bạn trở thành chuyên gia ở lĩnh vực nào đó. Mài giũa các kỹ năng của bạn theo hướng chuyên mốn hóa và thúc đẩy sự khám phá và tìm tòi. Đây là 1 năm tuyệt vời để làm điều gì đó tâm linh hoặc khám phá siêu hình học.\n\nĐây cũng là năm chăm sóc bản thân. Hãy dành thời gian cho chính mình. Hòa mình vào thiên nhiên hoặc tắm mình trong dòng nước sẽ tạo nên điều kỳ diệu cho tâm hồn bạn. Đây cũng là thời điểm tốt để bắt đầu tập thiền hoặc yoga. \n\nBạn có thể sẽ cảm thấy mình thích ẩn mình ở 1 vài thời điểm trong năm này, thích ở nhà hơn là ra ngoài. Tuy nhiên, bạn phải đề phòng bệnh trầm cảm. Năm 7 buộc bạn phải đánh giá cuộc sống và cảm xúc của mình.",
  8: "Năm cá nhân 8 là về vòng quay tiền bạc. Bất cứ điều gì cũng cũng có thể xảy ra trong năm này - bạn có thể trúng xổ số hoặc bị phá sản. Quyền lực, dù tốt hay xấu, là điều bạn có thể đạt được trong năm này. Đây là 1 năm tuyệt vời để thăng tiến hoặc bắt đầu công việc kinh doanh riêng của bạn.\n\nBạn cũng nhận được nhiều phần thưởng và thành quả. Đây là sự phản ánh trực tiếp những nỗ lực bạn đã bỏ ra trong suốt từ năm 1 đến năm 8. Lợi ích vật chất, thành công, sự ổn định về tài chính và địa vị đều nằm trong tầm tay. Một lời cảnh báo nhỏ cho số 8 là con số cho sự đảo ngược hoàn toàn, vì vậy, bạn có thể dễ dàng nhận thấy mình đang đi từ cao xuống thấp, thế nhưng thành quả đạt được tương xứng với những nỗ lực bạn đã bỏ ra trước đó.\n\nNếu bạn nghĩ về điều gì, hãy hành động ngay bây giờ. Ở năm 9, sẽ là quá muộn để bắt đầu những nỗ lực mới. Đây là cơ hội cuối cùng của bạn trước khi trở lại năm 1.\nHãy thận trọng, đừng làm mọi thứ phức tạp hơn mức cần thiết. Sự cân bằng và tính xác thực là nơi phép thuật của bạn sẽ được tìm thấy.",
  9: "Đây là năm để hoàn thành mọi thứ và buông bỏ những điều không có ích với bạn. Bạn đã đạt đến cuối chu kỳ 9 năm của mình và sẵn sàng nhận được phần thưởng từ tất cả sự phát triển và làm việc chăm chỉ của mình trước đó.\n\nNếu bạn cố gắng bắt đầu thứ gì đó trong năm 9, như các mối quan hệ hoặc 1 công việc mới, chúng có thể sẽ không kéo dài. Lòng dũng cảm và sức mạnh của bạn sẽ chịu thử thách trong năm này. Các mối quan hệ độc hại sẽ biến mất và các vấn đề kéo dài có thể tìm ra cách giải quyết. Đây là thời gian để kết thúc và chữa lành.\n\nTha thứ là điều quan trọng lúc này. Hãy buông bỏ quá khứ để nhường chỗ cho tương lai phía trước. Bạn không muốn phải bực bội với vị khách không phải trả tiền phòng trong khi bạn có 1 khách thuê mới thú vị triển vọng trong năm 1 tới đây. Hãy ''dọn chỗ'' cho những ước mơ lớn và lập kế hoạch.",
  11: "Năm này là thời gian để nuôi dưỡng những hạt giống bạn đã gieo mầm vào năm 1. Thời gian của bạn sẽ được sử dụng tốt để chăm sóc những ý tưởng lớn mà bạn đã đề ra vào năm trước.\n\nBạn sẽ có những kết nối mạnh mẽ và gặp gỡ những người có thể giúp bạn đạt được mục tiêu và ước mơ của mình. Đây là thời điểm tuyệt vời cho những mối quan hệ lãng mạn và xây dựng gia đình.\nNăm này diễn biến chậm hơn 1 chút so với năm trước, và sự kiên nhẫn và khă năng thỏa hiệp của bạn sẽ được thử thách. Bạn cũng sẽ trải qua những việc liên quan đến sự nhạy cảm.\n\nNếu hình dung 11 như 2 số 1 đi cùng nhau (kết hôn, sinh con) hoặc tách  rời nhau (ly hôn, sự ra đi của 1 người thân yêu) bạn sẽ thấy năm này liên quan đến các sự kiện hoặc mối quan hệ định mệnh như thế nào. Bạn có trực giác nhạy bén, vì vậy hãy tin vào  bản năng của mình.\nHãy lưu ý xem mình có đang bị lôi kéo, bướng bỉnh hay ích kỷ không, điều này bắt nguồn từ mức rung động thấp của năng lượng kép của 2 số 1.",
  22: "Hãy tập trung và tận tâm: Điều này yêu cầu việc chú tâm vào chi tiết, hiểu sự trì hoãn và tuân theo các quy tắc. Nếu phá vỡ các quy tắc, bạn sẽ phải gánh chịu hậu quả. Nếu tăng tốc, bạn sẽ đuổi kịp, nếu nói dối, bạn sẽ bị lộ. Hãy cẩn thận đừng bỏ bê sức khỏe của mình. Hãy kiểm tra sức khỏe định kỳ.\n\nThông điệp của năm này là về sự buông bỏ và học cách tin tưởng vào cảm nhận thiên tính. Hãy tuân theo tự nhiên và đừng ép buộc thứ gì, nếu không chúng sẽ phản tác dụng, một cách tệ hại!\n\nNăm vua 22: Là thời điểm bạn sắp xếp mọi thứ theo thứ tự, tạo nền tảng để xây dựng ước mơ của mình. Bài học của bạn sẽ bao gồm việc kiểm soát cái tôi và học cách vượt qua những trở ngại mà bạn không thể kiểm soát. Điều quan trọng là bạn phải tin tưởng người khác như một phần trong kế hoạch tổng thể của mình.",
  33: "(Giống số 6) Năm cá nhân 6 của bạn kiểm soát quan hệ hôn nhân, việc sinh con hay liên quan đến cái chết, gia đình, nhà cửa và thậm chí cả vật nuôi của bạn. Bản chất ma quỷ/thiên thần của số 6 cũng áp dụng cho năm này.\n\nNăm 6 cũng kiểm soát việc học hành, vì vậy bạn có thể thấy mình quay trở lại trường học hoặc tham gia các lớp học hoặc hội thảo vào cuối tuần. Đây là 1 năm tuyệt vời để học được điều gì đó mới. Từ tính cá nhân của bạn rất mạnh trong năm nay, vì vậy đây có thể là một năm thành công của mối quan hệ lãng mạn và chinh phục.\n\nBạn có thể thấy một vài điều tốt nhất và một vài sự kiện khó khăn nhất về mặt cảm xúc trong cuộc đời bạn sẽ xảy ra trong năm 6. Bạn có thể  kết hôn, và vài tháng sau, mất một vài người thân hoặc thú cưng.",
};

export const KARMIC_LESSON_TEXT = {
  1: "Thiếu A,J, hoặc S: Bạn sẽ học cách đứng lên bảo vệ chính mình và thúc đẩy bản thân. Bài học của bạn là tính độc lập và chủ động.",
  2: "Thiếu B,K hoặc T: Bạn sẽ học tính kiên nhẫn, tinh thần hợp tác và cần có sự khéo léo và khả năng ngoại giao tốt hơn. Bài học nghiệp của bạn sẽ là nhạy bén đối với cảm xúc của người khác và tinh thần hợp tác trong 1 đội.",
  3: "Thiếu C,L hoặc U:  Bài học này sẽ dạy bạn về giá trị của tình yêu bản thân và cách không quá nghiêm trọng hoặc tự phê bình bản thân. Bạn sẽ được thử nghiệm trong các lĩnh vực truyền thông và sáng tạo và học cách rèn luyện niềm vui và tinh thần lạc quan.",
  4: "Thiếu D,M hoặc V: Nếu bạn thiếu 1 trong các chữ cái này, bạn sẽ gặp khó khăn để duy trì tính tổ chức. Bạn cần xây dựng nền tảng và học kỷ luật để tránh phân tán năng  lượng của mình. Sự trì hoãn là vấn đề bạn phải khắc phục.",
  5: "Thiếu E,N hoặc W: Bạn sẽ học cách đón nhận thay đổi và trải nghiệm mới. Bài học của bạn là tìm kiếm 1 cuộc phiêu lưu trong cuộc sống và vượt qua nỗi sợ hãi bằng cách tin tưởng vào kế hoạch của vũ trụ.",
  6: "Thiếu F,O hoặc X: Bạn phải đối mặt với những vấn đề lớn liên quan đến tính cam kết và sự khó khăn trong thể hiện cảm xúc. Bạn né tránh 1 cách có trách nhiệm và phải nỗ lực trong việc xây dựng các mối quan hệ chân thành, dễ bị tổn thương. Có thể những vết sẹo gia đình cần được giải quyết hoặc tha thứ.",
  7: "Thiếu G,P hoặc Y: Bạn phải học bài học về tính xác thực và tìm kiếm sự giác ngộ tâm linh. Bạn có thể gặp khó khăn với việc học tập và trường lớp. Hãy cố gắng duy trì để tích lũy kiến thức chuyên môn và hoàn thiện tài năng của bạn.",
  8: "Thiếu H, Q hoặc Z:  Bài học của bạn là về cách quản lý tiền, cả khi dư thừa và túng thiếu. Bạn sẽ học cách xử lý các nguồn lực của mình, nhượng bộ hơn các nhân vật có thẩm quyền và chấp nhận lời khuyên của người khác.",
  9: "Thiếu I hoặc R: Bạn thiếu sự đồng cảm, tinh thần nhân đạo và sẽ học cách yêu thương, thấu hiểu và bao dung hơn. Bạn sẽ phải hi sinh tham vọng cá nhân vì lợi ích chung. Bạn sẽ hiểu được tầm quan trọng của cộng đồng và sự tha thứ.",
};

export const ARROWS = [
  {
    name: "SỰ KIÊN ĐỊNH",
    digits: [1, 5, 9],
    presentText: "Biểu đồ ngày sinh có cả 3 số 1,5,9 hoặc họ và tên có cả các chữ cái A/J/S, E/N/W, I/R : Chỉ sự kiên định, lòng quyết tâm, sự kiên trì, ý chí, động lực hoặc khả năng vượt qua nghịch cảnh.",
    absentText: "Biểu đồ ngày sinh thiếu cả 3 số 1,5,9 hoặc họ và tên thiếu cả các chữ cái A/J/S, E/N/W, I/R : Chỉ tính hay trì hoãn: Thiếu động lực, thiếu quyết đoán, nhút nhát, thờ ơ và dễ đầu hàng.",
  },
  {
    name: "SỰ TÂM LINH",
    digits: [3, 5, 7],
    presentText: "Biểu đồ ngày sinh có cả 3 số 3,5,7 hoặc họ tên có cả các chữ cái C/L/U, E/N/W, G/P/Y: Chỉ sự tâm linh: Lòng đồng cảm, thiên tính, niềm tin tâm linh mạnh mẽ và trực giác ẩn giấu.",
    absentText: "Biểu đồ ngày sinh thiếu cả 3 số 3,5,7 hoặc họ và tên thiếu cả các chữ cái C/L/U, E/N/W, G/P/Y: Chỉ sự hoài nghi: Thiếu tinh thần tâm linh, ít nhận thức cảm xúc, luôn nghi ngờ.",
  },
  {
    name: "TRÍ TUỆ",
    digits: [3, 6, 9],
    presentText: "Biểu đồ ngày sinh có cả 3 số 3,6,9 hoặc họ tên có cả các chữ cái C/L/U, F/O/X, I/R: Chỉ trí tuệ: Thông minh, logic, có trí nhớ đặc biệt, người nghiên cứu, giải quyết vấn đề.",
    absentText: "Biểu đồ ngày sinh thiếu 3 số 3,6,9 hoặc họ tên thiếu cả các chữ cái C/L/U, F/O/X, I/R: Chỉ điểm yếu về trí nhớ: Hay quên, kém tập trung, thiếu thông cảm, không quan tâm, trốn tránh trách nhiệm.",
  },
  {
    name: "CÂN BẰNG CẢM XÚC",
    digits: [2, 5, 8],
    presentText: "Biểu đồ ngày sinh có cả 3 số 2,5,8 hoặc họ tên có cả các chữ cái B/K/T, E/N/W, H/Q/Z: Chỉ sự cân bằng: Cảm xúc bị khuếch đại, cảm thông, nghiêm túc.",
    absentText: "Biểu đồ ngày sinh thiếu cả 3 số 2,5,8 hoặc họ tên thiếu cả các chữ cái B/K/T, E/N/W, H/Q/Z: Chỉ sự siêu nhạy cảm: Nhạy cảm, cảm giác tự ti, sợ hãi, khao khát được chữa lành.",
  },
  {
    name: "SỰ THỰC TIỄN",
    digits: [1, 4, 7],
    presentText: "Biểu đồ ngày sinh có cả 3 số 1,4,7 hoặc họ tên có cả các chữ cái A/J/S, D/M/V, G/P/Y: Chỉ sự thực tiễn: Âm nhạc, sáng tạo, các công việc tay chân, trách nhiệm tài chính.",
    absentText: "Biểu đồ ngày sinh thiếu cả 3 số 1,4,7 hoặc họ tên thiếu cả các chữ cái A/J/S, D/M/V, G/P/Y: Chỉ sự thiếu thực tiễn: Mơ mộng, viển vông, chi tiêu quá mức, sức khỏe có vấn đề",
  },
  {
    name: "TÍNH HAY LẬP KẾ HOẠCH",
    digits: [1, 2, 3],
    presentText: "Biểu đồ ngày sinh có cả 3 số 1,2,3 hoặc họ tên có cả các chữ cái A/J/S, B/K/T, C/L/U: Chỉ tính hay lập kế hoạch: Có tổ chức, kỷ luật, có kỹ năng, thành công.",
    absentText: "Biểu đồ ngày sinh thiếu cả 3 số 1,2,3 hoặc họ tên thiếu cả các chữ cái A/J/S, B/K/T, C/L/U: Chỉ sự bối rối: Nhầm lẫn, bối rối, thiếu tổ chức, thiếu cam kết, hiểu lầm.",
  },
  {
    name: "Ý CHÍ",
    digits: [4, 5, 6],
    presentText: "Biểu đồ ngày sinh có cả 3 số 4,5,6 hoặc họ tên có cả các chữ cái D/M/V, E/N/W, F/O/X: Thể hiện ý chí: Quyết đoán, ý chí mạnh, tập trung, kiên trì, vững vàng.",
    absentText: "Biểu đồ ngày sinh thiếu cả 3 số 4,5,6 hoặc họ tên thiếu cả các chữ cái D/M/V, E/N/W, F/O/X: Chỉ sự thất bại: Thất vọng, thiếu quyết đoán, kháng cự sự thay đổi.",
  },
  {
    name: "HOẠT ĐỘNG",
    digits: [7, 8, 9],
    presentText: "Biểu đồ ngày sinh có cả 3 số 7,8,9 hoặc họ tên có cả các chữ cái G/P/Y, H/Q/Z, I/R: Chỉ hoạt động: Sức chịu đựng, dẻo dai, năng lượng, hoạt động.",
    absentText: "Biểu đồ ngày sinh thiếu cả 3 số 7,8,9 hoặc họ tên thiếu cả các chữ cái G/P/Y, H/Q/Z, I/R:: Chỉ sự lưỡng lự: Chần chừ, lười biếng, thiếu niềm tin, vô tổ chức.",
  },
];

// Cường độ (số lần xuất hiện) của mỗi chữ số 1-9 trong Ma trận tên (Biểu đồ tên).
// Mỗi mục: { min, max (null = không giới hạn trên), text }.
export const NAME_CHART_TIERS = {
  1: [
    { min: 0, max: 0, text: "Không có số 1 nào: Thiếu tự tin và độc lập" },
    { min: 1, max: 3, text: "1 đến 3 số 1: Quyết đoán và có động lực" },
    { min: 4, max: 5, text: "4 đến 5 số 1: Mạnh mẽ, độc lập, nổi bật trong đám đông" },
    { min: 6, max: null, text: "6 số 1 trở lên: Hung hăng cạnh tranh, bướng bỉnh, hống hách, có thể hay bị đau đầu" },
  ],
  2: [
    { min: 0, max: 0, text: "Không có số 2 nào: Thiếu kiên nhẫn, thiếu chu đáo" },
    { min: 1, max: 1, text: "1 số 2: Chu đáo, sẵn sàng giúp đỡ, nhạy cảm" },
    { min: 2, max: null, text: "Có từ hơn 2 số 2: Khéo léo và chi tiết, có cảm nhận tốt về nhịp điệu và thời gian, gắn kết mọi người. Càng nhiều số 2: Càng nhạy cảm" },
  ],
  3: [
    { min: 0, max: 0, text: "Không có số 3 nào: Khó khăn trong việc giao tiếp và thể hiện bản thân" },
    { min: 1, max: 2, text: "1 đến 2 số 3: Dễ dàng thể hiện bản thân và cảm xúc của mình, đồng thời mang đến cho bạn khả năng tạo tiếng cười" },
    { min: 3, max: null, text: "Nhiều hơn 3 số 3: Tự cao, thiên về nghệ thuật, có năng khiếu ngôn từ, đôi khi hay suy nghĩ tản mạn, khó khăn trong duy trì sự tập trung" },
  ],
  4: [
    { min: 0, max: 0, text: "Không có số 4 nào: Vật lộn để duy trì tổ chức và tuân thủ, bạn cũng khó tập trung" },
    { min: 1, max: 2, text: "1 đến 2 số 4: Tính thực tế và khả năng nhìn thấu mọi thứ" },
    { min: 3, max: 5, text: "3 đến 5 số 4: Kỹ năng độc nhất để xây dựng những giá trị có tác động và lâu dài" },
    { min: 6, max: null, text: "Nhiều hơn 5 số 4: Bạn có tính kiểm soát, cứng rắn, bướng bỉnh và tham công tiếc việc" },
  ],
  5: [
    { min: 0, max: 1, text: "1 hoặc không có số 5 nào: Khó thích nghi với hoàn cảnh sống và không thích sự thay đổi và đám đông, khiến bạn trở nên tự cô lập" },
    { min: 2, max: null, text: "Sự tháo vát và khả năng thích ứng, có thêm số 5 tức là tăng cường năng lượng của con số này" },
  ],
  6: [
    { min: 0, max: 0, text: "Không có số 6 nào: Thiếu trách nhiệm, duy tâm và có những kỳ vọng không thực tế" },
    { min: 1, max: 2, text: "1 đến 2 số 6: Bạn sẽ không gặp khó khăn khi chịu trách nhiệm về các vấn đề nội bộ và gia đình cũng như tìm kiếm sự cân bằng trong cuộc sống" },
    { min: 3, max: 4, text: "3 đến 4 số 6: Quan điểm cá nhân mạnh mẽ, tính cách áp đảo và đòi hỏi cao" },
    { min: 5, max: null, text: "Nhiều hơn 5 số 6: Phải vật lộn quá nhiều với trách nhiệm gánh vác, bạn có thể thấy mình bị coi nhẹ hay bị lợi dụng" },
  ],
  7: [
    { min: 0, max: 0, text: "Không có số 7 nào: Cởi mở, không nghi ngờ, hoang tưởng nghĩa là bạn bốc đồng, thiếu tinh thần trong cuộc sống" },
    { min: 1, max: 1, text: "1 số 7: Tò mò, trực giác mạnh" },
    { min: 2, max: null, text: "Nhiều hơn 2 số 7: Không thích thể hiện cảm xúc, đầu óc máy móc và tỏ ra bí ẩn riêng tư" },
  ],
  8: [
    { min: 0, max: 0, text: "Không có số 8 nào: Thận trọng với nguồn lực của mình và bài học của bạn liên quan đến tiền bạc và quyền lực" },
    { min: 1, max: 2, text: "1 đến 2 số 8: Có năng lực và có thể chịu trách nhiệm khi cần thiết" },
    { min: 3, max: null, text: "Nhiều hơn 2 số 8: Giúp bạn hiểu rõ tiền nhưng cũng vì vậy bạn quá coi trọng đồng tiền trong cuộc sống của mình" },
  ],
  9: [
    { min: 0, max: 0, text: "Không có số 9 nào: Tự thu mình, bạn sẽ được thử thách bằng những bài học về lòng khoan dung và vị tha" },
    { min: 1, max: 1, text: "1 số 9: Không ý thức nhiều về cảm xúc của người khác" },
    { min: 2, max: null, text: "2 hoặc 3 số 9: Bạn hiểu biết, tài năng sáng tạo và cách tiếp cận nhân văn với cuộc sống" },
  ],
};
